### ISSUE TITLE
Unencrypted Application Binary

### ISSUE THREAD

**Issue by s2339956** [majd/ipatool#10]
This is the ipa file downloaded by "ipatool"

```
➜  ~ otool -l /Users/tinxie/Downloads/com.xxxxx.xxxxxx_284882215_v320.0_362/Payload/xxxxxx.app/xxxxxx | grep -B 2 crypt
          cmd LC_ENCRYPTION_INFO_64
      cmdsize 24
     cryptoff 16384
    cryptsize 3686400
      cryptid 1
```
 **cryptid 1**
the value of cryptid is 1 which shows that the application binary is encrypted. 
If for an application, the cryptid value is 0, it would mean that the application binary is unencrypted. 

can auto decrypt application binary files?

**Comment by majd** [comment]
No, this is currently unsupported and there are no plans to add support for decrypting the apps. All apps downloaded from the App Store are encrypted by default.
