### ISSUE TITLE
can not login

### ISSUE THREAD

**Issue by GH3a** [majd/ipatool#101]
### What happened?

ipatool auth login                            
==> ⚠️	[Warning] Enter Apple ID email:
==> ⚠️	[Warning] Enter Apple ID password:
==> ℹ️	[Info] Authenticating with the App Store...
zsh: segmentation fault  ipatool auth login

### Version

1.1.4

### Relevant log output

```shell
ipatool auth login                            
==> ⚠️	[Warning] Enter Apple ID email:
==> ⚠️	[Warning] Enter Apple ID password:
==> ℹ️	[Info] Authenticating with the App Store...
zsh: segmentation fault  ipatool auth login
```

**Comment by CreatorZZY** [comment]
I also meet such a problem.

**Comment by GH3a** [comment]
solved or not

> I also meet such a problem.

**Comment by majd** [comment]
Can you please try the latest RC build and see if the issue is resolved? https://github.com/majd/ipatool/releases/tag/v2.0.0-rc.2
