### ISSUE TITLE
Unable to login. Unknown error after entering 2FA code.

### ISSUE THREAD

**Issue by CraigSiemens** [majd/ipatool#110]
### What happened?

`login` always seems to fail with the message "An unknown error has occurred".

I tried using the `debug` log level that was suggested in other similar issues, but it didn't log an helpful information.

### Version

1.1.4

### Relevant log output

```shell
➜ ipatool auth login --log-level debug
==> ⚠️	[Warning] Enter Apple ID email:
==> ⚠️	[Warning] Enter Apple ID password:
==> 🛠	[Debug] Creating HTTP client...
==> 🛠	[Debug] Creating App Store client...
==> ℹ️	[Info] Authenticating with the App Store...
==> ⚠️	[Warning] Enter 2FA code:
==> 🛠	[Debug] unknownError
==> ❌	[Error] An unknown error has occurred.
```

**Comment by tarunVreddy** [comment]
Same issue here

**Comment by majd** [comment]
Can you please try the latest RC build and see if the issue is resolved? https://github.com/majd/ipatool/releases/tag/v2.0.0-rc.2
