### ISSUE TITLE
Unable to login

### ISSUE THREAD

**Issue by build-vtest** [majd/ipatool#112]
`login` always Fail with the message "`An unknown error has occurred`".

**ipatool version**: 1.1.4

**Reference snapshot**:
![image](https://user-images.githubusercontent.com/98380372/204457978-5b9569a9-94d2-4b04-b934-3206b8a6aeb6.png)

**Comment by build-vtest** [comment]
@majd - can you please help? am still stuck here on this issue..

**Comment by majd** [comment]
Can you please try the latest RC build and see if the issue is resolved? https://github.com/majd/ipatool/releases/tag/v2.0.0-rc.2
