### ISSUE TITLE
ERR error="required flag(s) \"email\" not set" success=false

### ISSUE THREAD

**Issue by The0verlay** [majd/ipatool#128]
### What happened?

Recibo el error ERR error="required flag(s) \"email\" not set" success=false al momento de autenticarme

### Version

2.0

**Comment by MMP0** [comment]
`email` parameter seems to be required in 2.0.0.
https://github.com/majd/ipatool/blob/8dd1a8508dc89f25f69c922f14292f15d0adda36/cmd/auth.go#L50

Try running: `ipatool auth login --email <Your Apple ID Email>`.
