### ISSUE TITLE
[Bug] failed to get account: failed to read item from keychain...

### ISSUE THREAD

**Issue by qnblackcat** [majd/ipatool#129]
### What happened?

I got this error when I run any ipatool's command. The tool was working perfectly fine before I update it to v2.0.0.

```ERR error="failed to get account: failed to read item from keychain: failed to get item from keyring: The specified item could not be found in the keyring" success=false```

I'm running macOS 11.6.4. ipatool (v2.0.0) was installed via Homebrew.

### Version

2.0.0

### Relevant log output

```shell
nguyendat@ ~ % ipatool search youtube --verbose
11:36PM DBG error="failed to get account: failed to read item from keychain: failed to get item from keyring: The specified item could not be found in the keyring" stack=[{"func":"(*appstore).Search","line":"19","source":"appstore_search.go"},{"func":"searchCmd.func1","line":"23","source":"search.go"},{"func":"(*Command).execute","line":"916","source":"command.go"},{"func":"(*Command).ExecuteC","line":"1044","source":"command.go"},{"func":"(*Command).Execute","line":"968","source":"command.go"},{"func":"Execute","line":"54","source":"root.go"},{"func":"main","line":"9","source":"main.go"},{"func":"main","line":"250","source":"proc.go"},{"func":"goexit","line":"1594","source":"asm_amd64.s"}]
11:36PM ERR error="failed to get account: failed to read item from keychain: failed to get item from keyring: The specified item could not be found in the keyring" success=false
```

**Comment by majd** [comment]
Starting from version 2.0.0, the tool requires you to be authenticated prior to using the search command. This is done to automatically infer the country code and other properties so that they no longer need to be specified.

You can authenticate using the `auth` command.
```
$ ipatool auth login -e <email>
```

**Comment by CySxL** [comment]
> Starting from version 2.0.0, the tool requires you to be authenticated prior to using the search command. This is done to automatically infer the country code and other properties so that they no longer need to be specified.
> 
> 
> 
> You can authenticate using the `auth` command.
> 
> ```
> 
> $ ipatool auth login -e <email>
> 
> ```

hope I'm not hijacking but does ipatool v2.0.0 has ios version ? I can't find it in Release tho.

**Comment by qnblackcat** [comment]
`$ ipatool auth login -e <email>`

Worked. Couldn‘t find this command anywhere tho
