### ISSUE TITLE
Need help on "enter 2FA code"

### ISSUE THREAD

**Issue by travisgu** [majd/ipatool#132]
When I used the tool on Macbook, I always stuck on the login step. The message shows:

11:55AM INF enter 2FA code:

I checked my ios devices and there was no code showing. Where can I find the 2FA code? Thanks.

**Comment by majd** [comment]
You can also get a code from your iOS or macOS devices by going to iCloud -> Security -> Get a Verification Code. Please note that the account you are logging in with should be the same one those devices are authenticated to. Another thing to keep in mind is sometimes you may get prompted for 2FA code even if the password and email address were incorrect, which is ineffective - please double check that as well.

**Comment by travisgu** [comment]
Thanks for your help. I can get the verification code now. @majd

**Comment by elburro1887** [comment]
Just for anyone else who was confused on iOS, the way to get there is:

Settings -> Your Account -> Password & Security -> Get Verification Code

**Comment by tejuamirthi** [comment]
even after entering the verification code from above approach, still getting some other error

**Comment by abartl** [comment]
You need to use the login command exactly the following way:
ipatool auth login --email=<YOUR EMAIL>
It will pop up also the 2FA code verification. My assumption is that other formats somehow don't get the parameters parsed correctly. So the following won't work:
ipatool auth login -email <YOUR EMAIL>
ipatool auth login -email=<YOUR EMAIL>

@tejuamirthi @majd 
> even after entering the verification code from above approach, still getting some other error `Failed to login`

**Comment by lobotomoe** [comment]
Experienced same issue. Reason is wrong password. Even if you typed wrong password you will asked 2FA. This is confusing a little.

**Comment by aleqx** [comment]
I'm inputting the correct password and still there is no 2FA being generated by any of my authenticated macbook pros (i don't have an iphone), and I can't generate a manual one either using the suggestino oin the readme. Using ipatool 2.3.1 and macos tahoe 26.5.1, which doesn't have a "get verification code" option in the login & security > two factor authentication pane (note how there is nothing underneath the security keys option) ... the README is confusing, or refers to older MacOS versions?

<img width="482" height="321" alt="Image" src="https://github.com/user-attachments/assets/84f68c53-b59f-44f7-9ac4-38ba4f5c3652" />
