### ISSUE TITLE
Cookie jar cannot load cookies

### ISSUE THREAD

**Issue by trevor-e** [majd/ipatool#135]
### What happened?

```
"failed to create appstore client: failed to create cookie jar: failed to create cookie jar: cannot load cookies: file locked for too long; giving up: cannot acquire lock: failed to create lock file /Users/administrator/.ipatool/cookies.lock open /Users/administrator/.ipatool/cookies.lock: file exists"
```

Saw this error when trying to download a batch of apps. I think this happened after some downloads failed due to rate-limiting, so my guess is that the appstore client does not clean up the lock file properly in that case. Was able to fix by removing the lock myself.

### Version

2.0.0

**Comment by majd** [comment]
Could you please provide instructions to reproduce the issue? Do you have a script that you used to download the batch of apps and that you can share?

**Comment by trevor-e** [comment]
I have my script running as a service and it essentially does:

```
ipatool auth login
ipatool download
```

I have it auth every time because it can be ~days between when this service is called and I'm not sure how long auth is valid for. Sometimes this service is called rapidly if I'm trying to download a list of apps, which I assume is the issue. I can update my script to be smarter about when `auth login` is needed.

**Comment by Al4ise** [comment]
You can use auth info to check if you're still authenticated
