### ISSUE TITLE
Output location

### ISSUE THREAD

**Issue by drewg233** [majd/ipatool#137]
### What happened?

Not sure if Im doing something wrong or not but for some reason when I download an ipa it downloads to the homebrew location. Is there a way to update the output location?

```
~/Downloads  ipatool download --bundle-identifier="BUNDLEID"
INF output=/opt/homebrew/bin/BUNDLEID.ipa success=true
```

### Version

2.0.1

**Comment by majd** [comment]
You can use the `--output` (short: `-o`) parameter to specify a custom output path. It should default to current working directory but there was a bug causing it to default to the executable path. It should be fixed in #142.
