### ISSUE TITLE
Support specify keyring backend in cmdline option

### ISSUE THREAD

**Issue by srdr0p** [majd/ipatool#139]
### Description

On MacOS, If run ipatool in remote SSH connection or third party terminal, ipatool will inherit parent process's security context, and thus has no permission to access Keychain, I think ipatool can change keyring backend to file to resolve this problem.

3:11PM ERR error="failed to get account: failed to read item from keychain: failed to get item from keyring: The specified item could not be found in the keyring" success=false

**Comment by majd** [comment]
Could you please provide exact steps to reproduce the issue? What third party terminal app can I use to trigger this error message?

**Comment by srdr0p** [comment]
I Use iTerm2
1. Enable SSH on localhost
2. Use another SSH client(remote or local) to connet the Mac
Note: MacOS's GUI is not started when user is not login, so even if user is login by remote SSH, Keychain unlock dialog will **never** appear.
