### ISSUE TITLE
Search Apps for iPad only

### ISSUE THREAD

**Issue by GH3a** [majd/ipatool#14]
If the App has both iPad & iPhone app, it is good to download it.
But when the App has only iPad app, there is no results of searching.

**Comment by GH3a** [comment]
https://apps.apple.com/app/dji-gs-pro/id1183717144
like this App

**Comment by majd** [comment]
Support for specifying the device family is available starting with [version 1.0.5](https://github.com/majd/ipatool/releases/tag/v1.0.5). Refer to the [readme](https://github.com/majd/ipatool/blob/main/README.md) for more information about the usage.
