### ISSUE TITLE
IPATool vs. iTunes 12.6.5.3 (version with apps support)

### ISSUE THREAD

**Issue by AymenKcm** [majd/ipatool#144]
### Description

Hello, 

Thanks for making the effort and release this tool. 

I was wondering: other than (possibly) the future ipatool feature that allows us to **downlad older versions of apps**, what does ipatool offer besides downloading IPA files ? iTunes v12.6.5.3 already does that with a much easier way (without having to enter commands in terminal, everything is in a GUI).

I know it is useful especially for developers, but for normal users that only want to save IPA files, does ipatool offer any advantage over iTunes ?

Thanks in advance.

**Comment by majd** [comment]
IPATool, as a tool, is targeted towards developers more than end users. It exposes an interface that you can use extend or reuse in your own apps and tools. In addition to that, the old iTunes version you mention is not available on every platform as far as I know. It could also stop working at any moment as it has been deprecated long ago.
