### ISSUE TITLE
Windows file format unsupported

### ISSUE THREAD

**Issue by EpIcInCoGnItO** [majd/ipatool#146]
Sorry for being a noob but after unzipping the tar zip.. the file that exists is basically unrecognisable on windows?

Please add a instruction for this? 
![image](https://user-images.githubusercontent.com/19586241/215414806-63952663-ac05-4a72-9b85-b54b445f849f.png)

**Comment by ViRb3** [comment]
You're using the `arm64` version, which is for only a handful of Surface laptops, you almost certainly meant to use the `amd64` version.

**Comment by EpIcInCoGnItO** [comment]
> You're using the a**rm**64 version, which is for only a handful of Surface laptops, you almost certainly meant to use the a**md**64 version.

Now using AMD64, I believe this is not support on intel based chips?

**Comment by EpIcInCoGnItO** [comment]
> amd64 is for Intel and AMD chips.

![image](https://user-images.githubusercontent.com/19586241/215632438-45428d8c-620e-48a1-b063-1172b42ab973.png)
Final extracted result

**Comment by EpIcInCoGnItO** [comment]
> I see the problem. You need to append ".exe" at the end of the file, it's missing the extension. So it needs to become:
> 
>     * ipatool-2.0.2-windows-amd64.exe
> 
> 
> This is indeed an issue with the packaging and needs to be fixed.

I changed it to exe and when I run it via cmd the pop up appears for a split second but goes away

**Comment by ViRb3** [comment]
Yes, it's a command line tool, you need to run it via Terminal, not double-click. Please do some research.

**Comment by EpIcInCoGnItO** [comment]
Finally got it working thanks

**Comment by ViRb3** [comment]
I'd keep this issue open since there's a bug in the windows packaging.
