### ISSUE TITLE
Support input 2FA: from github api

### ISSUE THREAD

**Issue by langkhach270389** [majd/ipatool#15]
Hi Dev. This project is amazing. I have using your  project  and remake it. Using siri shortcut + github actions. But if can support input 2FA code from github secrets env?
https://github.com/langkhach270389/ipatool-LK

Thanks you very much

**Comment by majd** [comment]
You're asking if the 2FA code can be be passed to `ipatool` without starting an interactive session, right? That's currently not supported but I will consider this as a feature request in that case.

Please note that the tool is distributed under the MIT license, please include a copy of that license in your scripts and make sure to link back to the original work (this repository).

**Comment by langkhach270389** [comment]
Okay. Sorry. I will update

**Comment by majd** [comment]
The desired behavior is now supported as of [version 1.0.6](https://github.com/majd/ipatool/releases/tag/v1.0.6).
