### ISSUE TITLE
Support SMS a2f

### ISSUE THREAD

**Issue by Natslol** [majd/ipatool#150]
### Description

it would be great if ipatool add SMS A2F support cause i don't have access to my phone with A2F, but i can still login to icloud or Apple by using SMS A2F.

**Comment by majd** [comment]
It is not possible to only enable 2FA via SMS. Your Apple ID will use SMS for 2FA if you do not have any other Apple device linked to the Apple ID at the time, otherwise it will send the code to one of the Apple devices. This flow is not customizable.

**Comment by tejuamirthi** [comment]
hey @majd even tho there are no other apple devices linked to my Apple ID, I still was not able to enable/get 2FA via SMS.

**Comment by kasnder** [comment]
I previously got SMS for 2FA, but am now not even getting any 2FAnotifications on an account that is actually connected to other iOS devices.

**Comment by DrJapan** [comment]
I don't seem to be getting the SMS notification or any sort of 2FA message. Any ideas?
