### ISSUE TITLE
Installation using Go not working properly

### ISSUE THREAD

**Issue by luisadnsaavedra** [majd/ipatool#152]
### What happened?

When running (in the project directory):
`go build -o ipatool`
 
I get this output:
```
github.com/majd/ipatool/cmd
cmd/root.go:20:18: undefined: version
```

### Version

Latest

### Relevant log output

```shell
github.com/majd/ipatool/cmd
cmd/root.go:20:18: undefined: version
```

**Comment by majd** [comment]
You need to run the script `./tools/version.sh` once prior to building with Go.
