### ISSUE TITLE
Error when downloading a app

### ISSUE THREAD

**Issue by N7WEra** [majd/ipatool#16]
Hi Majd

First of all thank you very much! this tool looks very useful!

Second, I'm getting the following error when trying to download apps (I tried multiple, this one I just choose randomly)

```user@MacOS % ipatool download -b sa.virginmobile.vm      
==> ℹ️	[Info] Querying the iTunes Store for 'sa.virginmobile.vm' in country 'US'...
==> ⚠️	[Warning] Enter Apple ID email:
==> ⚠️	[Warning] Enter Apple ID password:
==> ℹ️	[Info] Authenticating with the App Store...
==> ℹ️	[Info] Authenticated as 'XXXXX'.
==> ℹ️	[Info] Requesting a signed copy of '1439413116' from the App Store...
==> ❌	[Error] Your Apple ID does not have a license for this app. Download the app on an iOS device to obtain a license.
```

Do you know what's the error or how to solve it?

Thank you

**Comment by majd** [comment]
You need to download the app on an iOS device to obtain a license for it before you can use `ipatool`, as the error message already says.

> ==> ❌	[Error] Your Apple ID does not have a license for this app. Download the app on an iOS device to obtain a license.

**Comment by rehmatworks** [comment]
Isn't this possible to obtain a license using ipatool? Thanks for the awesome code though.
