### ISSUE TITLE
Specified keyring backend not available

### ISSUE THREAD

**Issue by ItzMiracleOwO** [majd/ipatool#160]
### What happened?

For every command:

-> ipatool auth login -e xxx@gmail.com -p Aa20080407
<- 2:26PM ERR error="failed to create appstore client: failed to create keyring: failed to open keyring: Specified keyring backend not available" success=false

### Version

2.3.2

### Relevant log output

```shell
2:31PM DBG error="failed to create appstore client: failed to create keyring: failed to open keyring: Specified keyring backend not available" stack=[{"func":"searchCmd.func1","line":"20","source":"search.go"},{"func":"(*Command).execute","line":"916","source":"command.go"},{"func":"(*Command).ExecuteC","line":"1044","source":"command.go"},{"func":"(*Command).Execute","line":"968","source":"command.go"},{"func":"Execute","line":"54","source":"root.go"},{"func":"main","line":"9","source":"main.go"},{"func":"main","line":"250","source":"proc.go"},{"func":"goexit","line":"1594","source":"asm_amd64.s"}]
2:31PM ERR error="failed to create appstore client: failed to create keyring: failed to open keyring: Specified keyring backend not available" success=false
```

**Comment by itsbrex** [comment]
@ItzMiracleOwO I encountered that error for some time. However, I managed to fix it by enclosing the email and password with single quotes, like this:

`ipatool auth login -e 'email@gmail.com' -p 'XXXXXXXXXXXXXXXXXXXXXXX' --auth-code '123456'`

> If your account has 2FA setup you need to click `Get Verification Code` in your iPhone's Settings > `Apple ID` (click your name) > `Password & Security` > `Get Verification Code` and then pass that in with the `--auth-code` flag.

<img src="https://user-images.githubusercontent.com/9772694/225390968-2da41149-f4ba-46ac-8250-e4d20a777d77.jpeg" width="35%" height="35%">

**Comment by majd** [comment]
@ItzMiracleOwO What OS are you running `ipatool` on? If it's macOS, are you connected via SSH or using a third-party terminal?

**Comment by ddomino007** [comment]
same error here, region is PL
directly in Terminal.app not blocking anything either

**Comment by kotori2** [comment]
I can reproduce this issue on Ubuntu 22.04 server (no desktop environment).
