### ISSUE TITLE
Windows tut pls

### ISSUE THREAD

**Issue by FURKAN100** [majd/ipatool#161]
### What happened?

can someone send a tut how to download and use the ipatool. ive come far but keep failing idk why. thanks

### Version

2.02

**Comment by ViRb3** [comment]
Please provide logs and exact reproduction steps. Your description leaves us no way to help you.

**Comment by FURKAN100** [comment]
Its not just one problem. I keep failing over and over. The Installation guide for windows is very short and that makes it difficult to understand what to do. Thats why I wanted to ask if anybody could do a step by step guide. 
What I did was:
1)download file (amd)
2)extract
3)opened cmd prompt with Windows + R and navigated with "cd" to the ipatool

**Comment by majd** [comment]
`ipatool` is a CLI tool so you need to use it from the command-line. If you need general support for using the CLI, please do some research. If you are having a specific issue with the tool, feel free to open a new issue.
