### ISSUE TITLE
Decrypting app installed via ipatool is weird and tricky

### ISSUE THREAD

**Issue by Amachik** [majd/ipatool#162]
### What happened?

hi, i just want to inform that decrypting an app installed via ipatool does not work most of the time . if installed via appstore all works normaly. im getting stuck at frameworks loading. not so sure how is ipatool different from appstore

### Version

2.0.2

**Comment by Amachik** [comment]
we tried 3 tools for app dump but all of them failed if the app was installed via ipatool.

**Comment by majd** [comment]
The tool downloads the app as it is from the App Store. The difference is that the binary is fat compared to the thinned binary that is downloaded specifically for your device if you use the App Store app on an iOS device. Make sure the tool that you are using supports this setup.

If there is an issue related to ipatool, feel free to post some logs and I'll reopen the issue.

**Comment by Amachik** [comment]
there is no other such a tool . Is it possible to download for specifically
for my device with ipa tool? Or is it possible to download only fat. I mean
it should be possible with user agents or not?

**Comment by majd** [comment]
The private App Store API that ipatool uses only allows retrieving the non-thinned app package.

**Comment by Amachik** [comment]
> The private App Store API that ipatool uses only allows retrieving the non-thinned app package.

we resolved the issue by removing some files from that fat ipa .

**Comment by YousufSSyed** [comment]
@Amachik Which files did you remove?
