### ISSUE TITLE
Logging with wrong parameter is marked successful but you are not logged in

### ISSUE THREAD

**Issue by AF-tl** [majd/ipatool#165]
### What happened?

When using ipatool auth login -email "sxsd@test.net"

You get a response:

`8:43AM INF email= name=" " success=true`

But you are not really logged in an can't use any of the features.
I would expect to get a more helpful error instead.

### Version

2.0.2

### Relevant log output

```shell
ipatool auth info
8:44AM INF email= name=" " success=true
```

**Comment by majd** [comment]
Do you by any chance have a hardware security key added to the Apple ID you are trying to authenticate with?
