### ISSUE TITLE
ipatool cant see subway surfers

### ISSUE THREAD

**Issue by Amachik** [majd/ipatool#176]
### What happened?

hi, this bundle id belongs to https://apps.apple.com/us/app/subway-surfers/id512939461
but ipatool cant see this game... any idea [why?[](url)](<img width="1202" alt="Screenshot 2023-05-01 at 16 45 49" src="https://user-images.githubusercontent.com/37242088/235470311-3a1bf8a6-85f2-48d2-b223-fce12a228bbd.png">)

### Version

latest

**Comment by ViRb3** [comment]
The `search` command matches the app name, not the bundleID. You need the new `lookup` command to match on bundleID, it is in git but not released yet.
