### ISSUE TITLE
Invalid credentials

### ISSUE THREAD

**Issue by mukut007** [majd/ipatool#19]
Hello, I try to download an app using the tool with my apple ID and password but it gives invalid credentials error. What could be the reason for this authentication error? The provided password is encrypted or plain text? 

==> ℹ️	[Info] Querying the iTunes Store for 'com.facebook.Facebook'...
==> ℹ️	[Info] Authenticating with the App Store...
==> ❌	[Error] Invalid credentials.

**Comment by majd** [comment]
Can't reproduce this. The password input should be your password in plain text. Keep in mind that app-specific passwords are not supported.
