### ISSUE TITLE
Error after running any command

### ISSUE THREAD

**Issue by aaronp613** [majd/ipatool#195]
### What happened?

When I try using ipatool (tried reinstalling already) I get this error: 

`panic: cannot load cookies: invalid character '<' looking for beginning of value`

The only commands that work are the help commands. 

### Version

2.1.1

### Relevant log output

```shell
panic: cannot load cookies: invalid character '<' looking for beginning of value

goroutine 1 [running]:
github.com/majd/ipatool/v2/pkg/util.Must[...](0x0?, {0x1009aa000?, 0x14000180410?})
	/Users/runner/work/ipatool/ipatool/pkg/util/must.go:6 +0x54
github.com/majd/ipatool/v2/cmd.newCookieJar({0x1009ad020?, 0x14000193370?})
	/Users/runner/work/ipatool/ipatool/cmd/common.go:59 +0xb0
github.com/majd/ipatool/v2/cmd.initWithCommand(0x14000244000)
	/Users/runner/work/ipatool/ipatool/cmd/common.go:124 +0x29c
github.com/majd/ipatool/v2/cmd.Execute()
	/Users/runner/work/ipatool/ipatool/cmd/root.go:58 +0x104
main.main()
	/Users/runner/work/ipatool/ipatool/main.go:10 +0x1c
```

**Comment by majd** [comment]
I would be interested in how you managed to end up in a state where the cookies file is damaged. I would suggest you clean up the config folder 

```sh
$ rm -rf ~/.ipatool
```

and authenticate again. See if you manage to reproduce the issue.

**Comment by aaronp613** [comment]
seems to have fixed the issue

**Comment by ddxv** [comment]
> I would be interested in how you managed to end up in a state where the cookies file is damaged. I would suggest you clean up the config folder

I believe I have ended up here recently after upgrades, though it could be that after upgrading is when I pay attention.


> ` $ rm -rf ~/.ipatool`

Confirmed this works each time followed by running the auth command.
