### ISSUE TITLE
m1 mac sideloading

### ISSUE THREAD

**Issue by ayouch** [majd/ipatool#20]
the IPAs downloaded through ipatool are working fine on m1 macs running 11.2.3 or below just like imazing would but apple stopped serving macOS compatible sinf data as you said and the 11.3 update stopped sideloading but you mentioned in the READ-ME that it's possible to get around that by using a jailbroken device so can you please give more details on how to exactly do that?
ps: I know it's not really an issue with your tool but I just hope that you will update the read me page with detailed steps.
thank you

**Comment by majd** [comment]
You will have to use download the ipa file using `ipatool`, install it on a jailbroken device and dump the decrypted data from memory to disk. Once you have done that, you can code sign ([can be ad-hoc](https://eclecticlight.co/2020/08/22/apple-silicon-macs-will-require-signed-code/)) the app package and install it successfully on the Apple Silicon mac.

**Comment by ayouch** [comment]
Thanks for your answer, I just have one more question: Will notifications work with this method? Because I haven't updated yet to try signing apps with an ad-hoc signature.
