### ISSUE TITLE
Failed to purchase item with param 'STDQ': failed to purchase app while using --purchase flag

### ISSUE THREAD

**Issue by dsevcik** [majd/ipatool#205]
### What happened?

I am facing this error everytime when downloading app with --purchase parameter. This happens both when using interactive and non-interactive mode. 
Similar issue happens while using ipatool purchase command separately.

### Version

1.1.3

### Relevant log output

```shell
ipatool --non-interactive --keychain-passphrase "some_pasphrase" download -b com.some.bundleid --purchase
```
ERR error="failed to purchase item with param 'STDQ': failed to purchase app" success=false

```
ipatool  purchase -b com.some.bundleid
```
INF enter passphrase to unlock "/root/.ipatool" (this is separate from your Apple ID password): 
ERR error="failed to purchase item with param 'STDQ': failed to purchase app" success=false

**Comment by tarantulaman** [comment]
The solution that worked for me was 

1. Run the purchase command
ipatool purchase -b com.google.photos

It should show an output like the following
8:30AM INF success=true

2. Then we download the application
ipatool download -b com.google.photos --purchase

**Comment by yuqiandoudou** [comment]
> The solution that worked for me was
> 
> 1. Run the purchase command
>    ipatool purchase -b com.google.photos
> 
> It should show an output like the following 8:30AM INF success=true
> 
> 2. Then we download the application
>    ipatool download -b com.google.photos --purchase

I dont work.
➜  ~  ipatool purchase -b com.app.ShiJi
10:32AM INF success=true
➜  ~ ipatool download -b com.app.ShiJi --purchase
downloading   0% |                                                                                                        | ( 0/ 1 B) 10:33AM ERR error="license is required" success=false

**Comment by davipt** [comment]
> ERR error="license is required" success=false

Have you by any chance “purchased” 300 apps in 24 hours? After 300 the purchase call apparently succeeds but then the download fails with that exact message. Wait some time and try again.

**Comment by AT5HK** [comment]
> The solution that worked for me was
> 
> 1. Run the purchase command
>    ipatool purchase -b com.google.photos
> 
> It should show an output like the following 8:30AM INF success=true
> 
> 2. Then we download the application
>    ipatool download -b com.google.photos --purchase

this fixed my issue

**Comment by Xuantam91** [comment]
> ➜ ~ ipatool pu

Hey, I have same issue. Can you share detail how to "It required to accept Terms & Conditions changes in the app store from the device conntcted to given apple ID" Thanks

**Comment by natlungfy** [comment]
I was able to overcome the STDQ/"license is required" error by first downloading the app on my Apple ID-connected iOS device. Then the purchase command worked for me.
