### ISSUE TITLE
Possible to revisit specifying Appstore country?

### ISSUE THREAD

**Issue by Q45cd** [majd/ipatool#208]
### Description

Hi Majd,

Is it possible to revisit the ability to specify Appstore country in search, download and purchase?

Although 1 and 2 are available in previous versions, it is not possible to download now without a license.

Cheers.

**Comment by majd** [comment]
The tool was never able to download or purchase apps in a different country's storefront other than the one linked to the Apple ID. This is simply not supported by the private App Store API. The "country code" option was removed to prevent this exact confusion. 🙂

**Comment by lockieluke** [comment]
still want the search function tho
