### ISSUE TITLE
Keychain Passphrase

### ISSUE THREAD

**Issue by AhmadAradii** [majd/ipatool#209]
### What happened?

Hi @majd 

I tried to use the tool on Windows but every time i try to authenticate i get this:

`INF enter passphrase to unlock "C:\\Users\\TOSHIBA\\.ipatool" (this is separate from your Apple ID password):`

How to get this passphrase

### Version

2.1.3

**Comment by AhmadAradii** [comment]
> you just set it and it will be asked everytime you do action

Please explain.

**Comment by Niggolo** [comment]
First time it is being asked write anything you want and remember it, every time you try to download or search or anything it won’t ask you Apple ID and password Instead it just ask the passphase

**Comment by AhmadAradii** [comment]
> First time it is being asked write anything you want and remember it, every time you try to download or search or anything it won’t ask you Apple ID and password Instead it just ask the passphase. Aleast this is what I figured and it worked

That's the thing is when i type anything it will give me this error:
`ERR error="failed to save account in keychain: failed to set item: open C:\\Users\\TOSHIBA\\.ipatool\\account: is a directory" success=false`

**Comment by Niggolo** [comment]
No idea, wait for developer or someone else that know much then me

**Comment by majd** [comment]
Try to deleting the config folder for ipatool at `C:\\Users\\TOSHIBA\\.ipatool` and authenticate again.

**Comment by AhmadAradii** [comment]
> Try to delete the config folder for ipatool at `C:\\Users\\TOSHIBA\\.ipatool` and authenticate again.

It Worked! Thanks a lot!
