### ISSUE TITLE
Purchase error ipatool

### ISSUE THREAD

**Issue by Cpmjaguar1234** [majd/ipatool#210]
### What happened?

I have signed into my apple account with auth but when I try to purchase a license, I get this error:  % ipatool purchase --bundle-identifier com.apple.TestFlight
3:00PM ERR error="failed to purchase item with param 'STDQ': Sign-In Required" success=false

**Can anyone help?**

### Version

ipatool version 2.1.3

**Comment by majd** [comment]
Try to singing into your Apple ID on an iOS device via the App Store. There could be updated legal terms or some popup that you need to accept.
