### ISSUE TITLE
Applying patches fails for Pages and Numbers apps

### ISSUE THREAD

**Issue by gregggreg** [majd/ipatool#212]
### What happened?

When attempting to download Apple's iWork apps Pages (https://apps.apple.com/us/app/pages/id361309726) and Numbers (https://apps.apple.com/us/app/numbers/id361304891), I get the following error:

1:39PM ERR error="failed to apply patches: failed to open zip reader: zip: not a valid zip file" success=false

I would expect the IPA to be properly downloaded, but it fails consistently on these two apps.

### Version

2.1.3 on macos

### Relevant log output

```shell
1:39PM ERR error="failed to apply patches: failed to open zip reader: zip: not a valid zip file" success=false
```

**Comment by majd** [comment]
I am unable to reproduce this issue. Are you able to check somehow that the downloaded zip file is indeed invalid?

**Comment by gregggreg** [comment]
Yeah I'm not seeing this issue anymore either for these apps. Looks like it was a temporary issue where maybe Apple was serving out invalid zip files for these apps? Will re-open if I see it again, but looks like it may not have been an issue with ipatool.

**Comment by davipt** [comment]
I’ve seen this happening when an app is macOS only. For example, downloading the Apple Configurator app (app_id 1037126344 bundle com.apple.configurator.ui) will yield an IPA file, but this is NOT a zip file.

I could guess the first time you downloaded the macOS version and the second the iOS version. Is there any chance you used a new account that logged in to a Mac first, earning the free “iTools” licenses, and after using ipatool the first time when it got the non Zip files, you’ve logged in on an iPhone or iPad, earning the license for the iOS versions?

I’ve seen these Mac Apps but haven’t yet got time to investigate what the IPA file is, not being a zip.
