### ISSUE TITLE
only support the US app store?

### ISSUE THREAD

**Issue by AppleTidusDev** [majd/ipatool#218]
### What happened?

Hi majd，
I use this tool to login to the apple id in China（account in China）.But the login failed.

ERR error="This Apple\u00a0ID has not yet been used with the iTunes Store." success=false

But if I use an apple id in the United States, I can successfully login
China app can also be searched, but not downloaded.

ERR error="license is required" success=false

I also read Issus #208
Still not sure if the tool will work on app stores outside the US？

### Version

2.1.3

**Comment by majd** [comment]
As the error message suggests, you need to use the App Store once with the Apple ID on any iOS device before you can use it with ipatool. The tool itself supports other stores than the US store.
