### ISSUE TITLE
Can't download the latest version of ipa when the app store already updated

### ISSUE THREAD

**Issue by XhivaW** [majd/ipatool#219]
### What happened?

Hi Majd, thx for the useful tool. 

I've meet a problem as the title says.

### Version

2.1.3

### Relevant log output

```shell
> ipatool search miHoYo -l 1              
10:28AM INF apps=[{"bundleID":"com.miHoYo.Yuanshen","id":1467190251,"name":"原神-4.0枫丹开放","price":0,"version":"4.0.0"}] count=1
> ipatool download -b com.miHoYo.Yuanshen
downloading   0% |                                                                              | (1.1 MB/2.6 GB, 210 kB/s) ^C
> ls
com.miHoYo.Yuanshen_1467190251_3.8.0.ipa.tmp
> ipatool -v   
ipatool version 2.1.3
```

**Comment by majd** [comment]
Is this still the case now? The lookup step uses the public iTunes search API while the download step uses the AppStore API. A few hours of delay after new version releases is to be expected.

**Comment by XhivaW** [comment]
> 

Hi majd, thx for replay and the download is consistent with search result now. And just wonder if it's possible to avoid such delay?
