### ISSUE TITLE
can i download the special device ipa(eg: iPhone12 or iPhone XR)

### ISSUE THREAD

**Issue by ticsmatic** [majd/ipatool#22]
Nice util. but i need download the special device ipa, did ipatool support this feature?

**Comment by majd** [comment]
The ipa package downloaded using `ipatool` is not thinned, which means it should work on all device variants. Is there a use-case for why you'd want a device-specific package?

**Comment by ticsmatic** [comment]
> The ipa package downloaded using `ipatool` is not thinned, which means it should work on all device variants. Is there a use-case for why you'd want a device-specific package?

1)I wonder my ipa size at Apple Connect  build activity is not accurate,  so i want to know the real ipa that the user will download
2)I want to learn the detail that Apple did for package slim(different device)

**Comment by majd** [comment]
Thanks for the info. Unfortunately, the API that `ipatool` uses only returns the URL for the universal app package so downloading a pre-thinned package is not possible. You may be able to replicate the way that the App Store distributes your own app by using the "Rebuild from Bitcode" option when distributing an app from Xcode's Organizer - but this is only limited to your own app as far as I know. 

Closing this issue for now.
