### ISSUE TITLE
Getting error after running command ipatool auth login --email and providing password with 2FA

### ISSUE THREAD

**Issue by skadoosh07** [majd/ipatool#220]
### What happened?

The error I am getting is 
<img width="594" alt="Screenshot 2023-08-25 at 12 48 53 AM" src="https://github.com/majd/ipatool/assets/55937942/e80fcee0-6c3a-4aee-b72f-bd5b675f4672">

Don't know how to proceed with it.

### Version

dev

**Comment by andy-3000** [comment]
this is on Linux, right?

**Comment by skadoosh07** [comment]
thanks, the error got resolved
