### ISSUE TITLE
Getting error by downloading ipa

### ISSUE THREAD

**Issue by 0th3rs1d3** [majd/ipatool#221]
### What happened?

when trying to download the ipa file following error appears
<img width="827" alt="image" src="https://github.com/majd/ipatool/assets/133700601/748ddf1d-01d1-435b-ac3e-338ec5cfd444">

( i use windows)

### Version

2.1.3

### Relevant log output

```shell
-
```

**Comment by majd** [comment]
Are you still able to reproduce this issue?

**Comment by 0th3rs1d3** [comment]
yes error still appears

**Comment by 168178218-myseneca** [comment]
Any solutions to this error? I have the same issue right now

**Comment by mikesTech** [comment]
> Any solutions to this error? I have the same issue right now

what operating system are you using

**Comment by 0th3rs1d3** [comment]
> > Any solutions to this error? I have the same issue right now
> 
> what operating system are you using? what version are you using? are you using the latest release

checked it again, not working. I am on windows 11 and use ipatool-2.1.4-windows-amd64

**Comment by mikesTech** [comment]
what version of go are you using?

**Comment by 0th3rs1d3** [comment]
i have go1.21.6, building it myself didn't work, so i downloaded the compiled version from the release tab
