### ISSUE TITLE
ipatool not prompting 2FA code on my devices 

### ISSUE THREAD

**Issue by jonahdecker** [majd/ipatool#224]
### What happened?

When I run `ipatool auth login -email stevejobs@apple.com` (fake email for privacy) and enter my password, I am asked for a 2FA authentication code. However, I am not getting a code on any of my devices. Using the `-password` flag doesn't work either. This prevents me from being able to download any ipa files. 

### Version

2.1.3

### Relevant log output

```shell
jonahdecker@Jonahs-MBP ~ % ipatool -v
ipatool version 2.1.3

jonahdecker@Jonahs-MBP ~ % ipatool auth login -email stevejobs@apple.com
1:23AM INF enter password:
1:23AM INF enter 2FA code:

1:23AM ERR error="auth code is required" success=false
```

**Comment by e-ave** [comment]
I get this too, and when i provide it via --auth-code command line, or try adding it to the end of the password (saw in another issues thread), I get this error

ERR error="Did you forget your password?" success=false

**Comment by ahbou** [comment]
same

**Comment by ahbou** [comment]
Found the issue.
My password has a space in it and since I was passing it using "--password my password" it was being cut out.

**Comment by majd** [comment]
Make sure that your credentials are correct. You can also retrieve the 2FA code from an iOS or Mac device that is already logged in via that Apple ID - using the Settings app.

**Comment by solidgonk** [comment]
If anyone else stumbles on this, try using '**--email=**email@domain.com' instead of '**-email** email@domain.com'

**Comment by gingerbeardman** [comment]
> Make sure that your credentials are correct. You can also retrieve the 2FA code from an iOS or Mac device that is already logged in via that Apple ID - using the Settings app.

Settings > Apple ID > Sign-in & Security > Two-Facto Authentication > Get Verification Code

But, it's still not working for me. 

I tried using password and also app-specific password.
