### ISSUE TITLE
failed to remove original file

### ISSUE THREAD

**Issue by mxmkmarquette** [majd/ipatool#225]
### What happened?

"ipatool-2.1.3-windows-amd64.exe" download --bundle-identifier ch.protonmail.vpn --output D:\files.ipa

ERR error="failed to remove original file: rename D:\\files.ipa.tmp D:\\files.ipa: The process cannot access the file because it is being used by another process." success=false

### Version

2.1.3

**Comment by ihjycc** [comment]
是的，我也遇到了相同的问题

**Comment by ndlaroy99** [comment]
I am having this issue as well. Running v2.1.3 on Windows 11

**Comment by majd** [comment]
Does this issue occur constantly for you?

**Comment by ndlaroy99** [comment]
Hi yes, it does.

**Comment by 0xS4D** [comment]
Same error here

**Comment by lolchikprekolchik** [comment]
someone solved this problem? bcuz i have it too

**Comment by majd** [comment]
This should be fixed once #249 is merged.
