### ISSUE TITLE
ERR error="received error: An unknown error has occurred"

### ISSUE THREAD

**Issue by Spygamer10** [majd/ipatool#226]
### What happened?

when ever i try to download a ipa this error shows up
ERR error="received error: An unknown error has occurred"
<img width="571" alt="Screenshot 2023-09-16 at 00 43 03" src="https://github.com/majd/ipatool/assets/88950166/6e4baa77-be0c-4778-8cf1-301e33377ffe">

### Version

2.1.3

### Relevant log output

```shell
malinidevi@Malinis-MacBook-Air ~ % ipatool download -b com.openai.chat
downloading   0% |                                                 | ( 0/ 1 B) 12:39AM ERR error="received error: An unknown error has occurred" success=false
```

**Comment by arm64x** [comment]
Today I had the same error as you, after about 1 hour it worked normally again.

**Comment by SpyGgG** [comment]
yeah it works now

**Comment by sstraus** [comment]
I'm still having the problem.

**Comment by e-ave** [comment]
Would love this to work....

**Comment by e-ave** [comment]
The actual error (shown when adding --verbose) is "CustomerMessage":"An unknown error has occurred","FailureType":"5002"

**Comment by e-ave** [comment]
I was not able to solve this with ipa tool. I suspected that you need to give ipatool your iOS device's MAC address, and I found someone elses python script that hardcodes the mac address and it works perfectly. I didnt try it but you can likely just hardcode your iOS device's MAC in the ipatool source code and compile it yourself. Not too sure why there isnt an option to pass a MAC address though....

**Comment by bzeifert** [comment]
I use the tool on macOS and can confirm it's an issue there as well. Also, the original screenshot in the issue suggests the user was on a MacBook Air.

I was using about 24 hours ago and experienced this error for about 1-2 hours before the tool recovered, and I was able to use it normally again for the next 3-4 hours. When I went to use the tool this morning (~8 hours ago), it was no longer working and has not been working since. I consistently get the error message cited above.

**Comment by sstraus** [comment]
Today it's working again

**Comment by neoighodaro** [comment]
Not for me it isnt

**Comment by neoighodaro** [comment]
> I was not able to solve this with ipa tool. I suspected that you need to give ipatool your iOS device's MAC address, and I found someone elses python script that hardcodes the mac address and it works perfectly. I didnt try it but you can likely just hardcode your iOS device's MAC in the ipatool source code and compile it yourself. Not too sure why there isnt an option to pass a MAC address though.... Seems that this is not an issue on mac, only windows/linux, so if the maintainers of ipatool are only testing on macOS that could be the issue.

@e-ave can you share which tool?

**Comment by RichTime1** [comment]
I also have this problem.

**Comment by asdfzxcvbn** [comment]
same. issue seems to be coming and going, works for a couple hours, stops working, and then starts working again soon

**Comment by asdfzxcvbn** [comment]
haven't experienced this for days. i think this issue can be closed.

**Comment by e-ave** [comment]
> > I was not able to solve this with ipa tool. I suspected that you need to give ipatool your iOS device's MAC address, and I found someone elses python script that hardcodes the mac address and it works perfectly. I didnt try it but you can likely just hardcode your iOS device's MAC in the ipatool source code and compile it yourself. Not too sure why there isnt an option to pass a MAC address though.... Seems that this is not an issue on mac, only windows/linux, so if the maintainers of ipatool are only testing on macOS that could be the issue.
> 
> @e-ave can you share which tool?

I was going to but my apple ID got banned so I wouldn't recommend it... https://gist.github.com/spawn9275/6303053b0fae58d5b777e2c6d9192a2d

I used this and I added a input in between the two auth POST requests like this:
`# Request it twice, the first one will result in a 302 response
# First request
auth = saved_session.post(url=auth_url, headers=auth_headers, data=auth_params)

# After the first request, you should get the 2FA code
# Check if the code file exists already first
if os.path.isfile(code_file_path):
    # Read the code from the file
    with open(code_file_path, "r") as file:
        code = file.read()
else:
    # Prompt the user to input the 2FA code
    code = input("Write 2FA code: ")

    # Save the code to the file for next time
    with open(code_file_path, "w") as file:
        file.write(code)

auth_params['password'] += code

# Second request
auth = saved_session.post(url=auth_url, headers=auth_headers, data=auth_params)`

I'm not totally sure why I got banned but I suspect it may be reusing the same 2fa multiple times. This script has no problem using the same 2fa code so I save it to a txt file and reuse it. It might be that the auth_params needs updated so a unique 2fa code is required every single time like with ipatool. Makes it impossible to automate though...

**Comment by majd** [comment]
Closing the issue for now. Let me know if this re-occurs.

**Comment by mfuhrer** [comment]
Trying out ipatool for the first time today (built from latest source tree). I'm running into this issue consistently - haven't had a successful download yet.

**Comment by mfuhrer** [comment]
Never mind, false alarm. Turns out my Apple ID was locked. Had to sign in from icloud.com to unlock my account. After logging in anew with
```shell
$ ipatool auth revoke
$ ipatool auth login -e email@domain.com
``` 
and entering my password and 2FA code, downloads are now running fine.

**Comment by Imgkl** [comment]
@e-ave what is the code_file_path you have added?

**Comment by FlashTang** [comment]
same here 
ERR error="received error: An unknown error has occurred" success=false

**Comment by FlashTang** [comment]
> The actual error (shown when adding --verbose) is "CustomerMessage":"An unknown error has occurred","FailureType":"5002"

Yes , mine  is 5002 too

**Comment by OscarVanL** [comment]
I got 5002 too.
