### ISSUE TITLE
ERR error="failed to reoslve the country code: country code mapping for store front () was not found"

### ISSUE THREAD

**Issue by veanome** [majd/ipatool#227]
### What happened?

ipatool suddenly will not download, search, or purchase anything since I keep running into this country code mapping error.

### Version

2.1.3

### Relevant log output

```shell
username@MacBook-Air ~ % ipatool auth login -e my.email@domain.com
11:30AM INF enter password:
11:30AM INF email= name=" " success=true
username@MacBook-Air ~ % ipatool download --bundle-identifier co.application.here --output /Users/username/Desktop/App.ipa
ERR error="failed to reoslve the country code: country code mapping for store front () was not found"
```

**Comment by marcoizzo** [comment]
I face a similar issue

**Comment by majd** [comment]
Is this issue still occurring?

**Comment by KhoraLee** [comment]
> Is this issue still occurring?

Yes, it still occurs
<img width="913" alt="image" src="https://github.com/majd/ipatool/assets/18005062/64a2ff31-b61d-439c-8199-87b7ccf1d358">

**Comment by veanome** [comment]
Yes the issue is still occurring. I tried it again just a few moments ago and get the same error.

**Comment by hzlzh** [comment]
same here

**Comment by majd** [comment]
I am unable to reproduce this issue so I will need your help to debug this. Have you used the Apple ID with the App Store before attempting to use it with ipatool?

**Comment by KhoraLee** [comment]
> I am unable to reproduce this issue so I will need your help to debug this. Have you used the Apple ID with the App Store before attempting to use it with ipatool?

I've removed ipatool related item in `Keychain Access` and after re-login it works.

Looks like this error happens when login is not done correctly.
Login result with empty email and blank name shouldn't be success. / ex ```12:32AM INF email= name=" " success=true```

**Comment by hzlzh** [comment]
> I am unable to reproduce this issue so I will need your help to debug this. Have you used the Apple ID with the App Store before attempting to use it with ipatool?

Yes I used those apple IDs on iPhone first and download some free app as a test, I also accept the popup.
So what to do next to debug?

**Comment by cloud-commander** [comment]
I had this issue too. I was able to resolve it by unlocking my Apple account on the web and resetting my password. I was then able to login successfully.

**Comment by hzlzh** [comment]
> I had this issue too. I was able to resolve it by unlocking my Apple account on the web and resetting my password. I was then able to login successfully.

It will happen again every day

**Comment by hzlzh** [comment]
@veanome Did you fix this? Could you tell me how?

**Comment by invasionofsmallcubes** [comment]
Having same issue here, is like if you do `ipatool auth login --email email@gmail.com` then you get as answer: `4:18PM INF enter password:` and if you put the password then you get `4:18PM INF email= name=" " success=true`

It seems email is empty and no actual authentication happens.

**Comment by fotiDim** [comment]
I am having this issue as well. Tried with 2 different accounts.

**Comment by kklints-rt** [comment]
I face same issue:

```
C:\Users\XXX\Downloads\ipatool-2.1.4-windows-amd64\bin>ipatool-2.1.4-windows-amd64.exe auth login -e user@mydomain.com
3:09PM INF enter password:
3:10PM INF enter 2FA code:
480728
3:10PM INF enter passphrase to unlock "C:\\Users\\XYZ\\.ipatool" (this is separate from your Apple ID password):
3:11PM INF email= name=" " success=true

C:\Users\XYZ\Downloads\ipatool-2.1.4-windows-amd64\bin>ipatool-2.1.4-windows-amd64.exe search cloudflare
3:11PM INF enter passphrase to unlock "C:\\Users\\XYZ\\.ipatool" (this is separate from your Apple ID password):
3:11PM ERR error="country code is invalid: country code mapping for store front () was not found" success=false
Search for iOS apps available on the App Store
```

**Comment by telnettrauma** [comment]
i am also facing the same issue

**Comment by alexacz** [comment]
When you log in, you have to provide email & password on the command line, otherwise you will have problems.

```bash
ipatool auth revoke
ipatool auth login -e YOUR_EMAIL -p YOUR_PASSWORD
```

**Comment by iDanbo** [comment]
> When you log in, you have to provide email & password on the command line, otherwise you will have problems.
> 
> ipatool auth revoke
> ipatool auth login -e YOUR_EMAIL -p YOUR_PASSWORD

this worked for me

**Comment by hzlzh** [comment]
> When you log in, you have to provide email & password on the command line, otherwise you will have problems.
> 
> ipatool auth revoke
> ipatool auth login -e YOUR_EMAIL -p YOUR_PASSWORD

not work

**Comment by invasionofsmallcubes** [comment]
It didn't work

**Comment by Teriand** [comment]
same issue for me, mb reopen @veanome ?
