### ISSUE TITLE
ERR error="failed to get account: failed to get item: The specified item could not be found in the keyring"

### ISSUE THREAD

**Issue by ImaTheWorstCoderEver** [majd/ipatool#231]
### What happened?

when downloading an ipa it just gives up and says
ERR error="failed to get account: failed to get item: The specified item could not be found in the keyring"
Absolutely stupid!
Please help

### Version

2.1.3

### Relevant log output

```shell
ERR error="failed to get account: failed to get item: The specified item could not be found in the keyring" success=false
```

**Comment by U5KUN** [comment]
Me too

**Comment by h-a-c** [comment]
Reauthenticating fixed it for me.

**Comment by ImaTheWorstCoderEver** [comment]
How do you Reauthenticate?

**Comment by everlof** [comment]
`ipatool auth login --email $your_mail`
