### ISSUE TITLE
request failed: request failed

### ISSUE THREAD

**Issue by panw3i** [majd/ipatool#232]
### What happened?

DBG error="request failed: request failed: Post \"https://p25-buy.itunes.apple.com/WebObjects/MZFinance.woa/wa/authenticate?guid=18C04D1C5A5E\": failed to make round trip: EOF"

### Version

V2.1.3

**Comment by ktiays** [comment]
I have also met the same problem.

**Comment by majd** [comment]
Are you able to reproduce this issue?

**Comment by t1996ys** [comment]
> Are you able to reproduce this issue?
i have some question
-->ipatool auth login -e email -p password
-->ERR error="request failed: request failed: Post \"https://p25-buy.itunes.apple.com/WebObjects/MZFinance.woa/wa/authenticate?guid=000C29ACDC89\": failed to make round trip: dial tcp: lookup p25-buy.itunes.apple.com on [::1]:53: read udp [::1]:59794->[::1]:53: read: connection refused" success=false

**Comment by Asi-Moo** [comment]
I finish the issuecheck your network!!

**Comment by Asi-Moo** [comment]
i finish the issue,

**Comment by Asi-Moo** [comment]
done:i solved the issue!   just check network!
