### ISSUE TITLE
Whar app want

### ISSUE THREAD

**Issue by QWERTYXss** [majd/ipatool#236]
i'm facing this problem. After entering the password  and 2fa, it asks to enter "passphrase", maybe i am stupid, but i really do not understand what it wants from me.Explaine please , i've been trying for 2 hours. Message " INF enter passphrase to unlock "C:\\Users\\User\\.ipatool" (this is separate from your Apple ID password):"

**Comment by majd** [comment]
This is the passphrase that you entered when using `ipatool` for the first time. If you forgot the passphrase, you can remove the `.ipatool` directory in your home folder and re-authenticate using `ipatool auth login`.
