### ISSUE TITLE
Random Throttles in Download Speed

### ISSUE THREAD

**Issue by iammanpreetsingh** [majd/ipatool#238]
### What happened?

IPATool is working fine, downloads great but randomly it throttles the download speed. Literally Randomly! And other times it works like a charm! I don't know why it's happening! Any help or advice would be appreciated. 

Here is the video:

https://github.com/majd/ipatool/assets/41124506/ca976d48-c267-49b0-9bf4-78d00ad598f1

### Version

2.1.3

**Comment by majd** [comment]
The files are shipped from Apple servers which might experience throttling under unknown circumstances. Unfortunately, there is not much that can be done about that.
