### ISSUE TITLE
Hey sir, how can i download an app?

### ISSUE THREAD

**Issue by CabbarNotFound** [majd/ipatool#242]
### What happened?

i download the ipatool and login with Apple ID, i tried the search apps and download but it says "ERR error="country code is invalid: country code mapping for store front () was not found" success=false" im new about coding and terminal but i need a app's older versions for download, what i need to do step-by-step? (MACOS)

### Version

Latest (2.1.3)

### Relevant log output

```shell
ERR error="country code is invalid: country code mapping for store front () was not found" success=false
```

**Comment by elzii** [comment]
Experiencing this again after a good 6 months of solid performance. I'm located in CA. On MacOS 14.1.1. Initially, I could search, but not download bundles -- now I cannot even search. Let me know in how I can assist you in debugging.

**Comment by CabbarNotFound** [comment]
I mean "How can i download and check old versions of an app with MacOS &
Ipatool?"

1 Oca 2024 Pzt 23:45 tarihinde Alexander Zizzo ***@***.***>
şunu yazdı:

**Comment by majd** [comment]
See #6. Downloading older versions of apps is currently not supported.
