### ISSUE TITLE
ERR error="required flag(s) \"email\" not set"

### ISSUE THREAD

**Issue by debasisj** [majd/ipatool#245]
### What happened?

2.1.3
installed latest through brew on Macbook Pro with Intel chip 
command - `ipatool auth login`

error - `ERR error="required flag(s) \"email\" not set" success=false`

Apple ID set up to use the App Store

### Version

2.1.3

### Relevant log output

```shell
ERR error="required flag(s) \"email\" not set" success=false
```

**Comment by iammanpreetsingh** [comment]
ipatool auth login -e email -p password

**Comment by majd** [comment]
Please use the email flag with the login command `ipatool auth login --email=<email>`.

**Comment by carlox97** [comment]
@majd Why isn't this in the readme?


> Please use the email flag with the login command `ipatool auth login --email=<email>`.
