### ISSUE TITLE
No long auth login just: INF email= name=" " success=true

### ISSUE THREAD

**Issue by hzlzh** [majd/ipatool#246]
### What happened?

11:50PM INF email= name=" " success=true

### Version

2.1.3

### Relevant log output

```shell
ipatool auth login -e xxx@xxx.com -p 123456
INF email= name=" " success=true
```

**Comment by fengyunyongjie** [comment]
我遇到了相同的错误,请问是如何解决的?

**Comment by hzlzh** [comment]
same here

**Comment by AhmadAradii** [comment]
> ### What happened?
> 11:50PM INF email= name=" " success=true
> 
> ### Version
> 2.1.3
> 
> ### Relevant log output
> ```shell
> ipatool auth login -e xxx@xxx.com -p 123456
> INF email= name=" " success=true
> ```

Are you sure that both email and password are correct?

**Comment by majd** [comment]
Did logging in again resolve the issue?

**Comment by MyFriendlyUserName** [comment]
Same issue here with version 2.1.4 (ARM64):
```
$ ipatool-2.1.4-macos-arm64 auth login -e <apple-id-email>
9:24AM INF enter password:
9:24AM INF email= name=" " success=true
```
When trying to search something:
```
$ ipatool-2.1.4-macos-arm64 search test
9:23AM ERR error="country code is invalid: country code mapping for store front () was not found" success=false
```
Country Code should be AT.

Thanks for your help!
