### ISSUE TITLE
crashes Windows

### ISSUE THREAD

**Issue by dgigurda** [majd/ipatool#252]
### What happened?

https://github.com/majd/ipatool/assets/56129208/fd2382f3-a873-4fd2-b004-daaabbdf86af
idk how to fix plz gimme some help PS:end of bug on 0:36
 ### Version

2.1.3

**Comment by AhmadAradii** [comment]
> ### What happened?
> https://github.com/majd/ipatool/assets/56129208/fd2382f3-a873-4fd2-b004-daaabbdf86af idk how to fix plz gimme some help PS:end of bug on 0:36
> 
> ### Version
> 2.1.3
> 
> ### Relevant log output
> _No response_

Please check my reply to the following case that should help you since both of you have the same issue:

https://github.com/majd/ipatool/issues/256
