### ISSUE TITLE
Does this utility support the UK  Apple store? 

### ISSUE THREAD

**Issue by bugwrangler** [majd/ipatool#26]
<img width="691" alt="Screenshot 2021-09-15 at 10 56 55" src="https://user-images.githubusercontent.com/6933052/133412884-0f25b436-c40e-4102-b738-9895e488ff28.png">

**Comment by majd** [comment]
The alpha-2 country code for the United Kingdom is `GB`. The command would be
```
ipatool search facebook --country GB
```
