### ISSUE TITLE
Cannot use -purchase command

### ISSUE THREAD

**Issue by astrohaley** [majd/ipatool#261]
### What happened?

Whenever I attempt to use the purchase command, I get this error

ERR error="failed to purchase item with param 'STDQ': Your password has changed." success=false

### Version

2.1.3

**Comment by Leo-MathGuy** [comment]
Try to log out and log in?

**Comment by astrohaley** [comment]
With my apple ID?

**Comment by Leo-MathGuy** [comment]
Yes

**Comment by majd** [comment]
This error usually implies that you need to authenticate again using the `auth` subcommand.
