### ISSUE TITLE
errors everywhere

### ISSUE THREAD

**Issue by Foxiseminger** [majd/ipatool#266]
### What happened?

C:\Users\Fox\Desktop>ipatool search --limit 1 TestFlight
9:01PM ERR error="failed to get account: failed to get item: The specified item could not be found in the keyring" success=false

C:\Users\Fox\Desktop>ipatool download --bundle-identifier com.apple.testflight
9:02PM ERR error="failed to get account: failed to get item: The specified item could not be found in the keyring" success=false

I am getting errors for some reason

### Version

the latest one

### Relevant log output

```shell
C:\Users\Fox\Desktop>ipatool search --limit 1 TestFlight
9:01PM ERR error="failed to get account: failed to get item: The specified item could not be found in the keyring" success=false

C:\Users\Fox\Desktop>ipatool download --bundle-identifier com.apple.testflight
9:02PM ERR error="failed to get account: failed to get item: The specified item could not be found in the keyring" success=false
```

**Comment by majd** [comment]
Remove the `.ipatool` folder from your home directory and authenticate again with the `auth` subcommand. This will create a new keyring. Make sure to note down the password you set there as you will need it every time you authenticate.
