### ISSUE TITLE
Where is tutorial for Windows user about how to use it?

### ISSUE THREAD

**Issue by sfksuperman** [majd/ipatool#276]
### What happened?

Where is tutorial for Windows user about how to use it?

### Version

2.1.4

**Comment by chocolate-byte** [comment]
--help

**Comment by csdamien** [comment]
Go to the file where the exe is located. Right click and open terminal. Copy the name of the app (ipatool-(version).exe), go back to terminal and write .\(paste) and then after that use the commands that are on the GitHub page
