### ISSUE TITLE
What can I do with an encrypted IPA?

### ISSUE THREAD

**Issue by sonvirgo** [majd/ipatool#278]
### Description

I have TrollStorem, SideLoadly. Both refuse to install encrypted IPA or state a warning during installation. App crash when open.
So what is the meaning of encrypted IPAs?

**Comment by truonglac2603** [comment]
Getting the same issue. Having bunch of encrypted ipa files and can not install with either Esign, Trollstore or Filza. Is there a workaround to install those file to my ios devices?

**Comment by JPS46225** [comment]
Just install them via the AppStore.

**Comment by truonglac2603** [comment]
> TrollStore needs ipas to be decrypted. But you're better off just installing them via the AppStore.

Thanks for your reply, but i don't really catch it. You mean Appstore can install encrypted ipa? Or just install the app directly from Appstore?

**Comment by JPS46225** [comment]
> > TrollStore needs ipas to be decrypted. But you're better off just installing them via the AppStore.
> 
> Thanks for your reply, but i don't really catch it. You mean Appstore can install encrypted ipa? Or just install the app directly from Appstore?

Yeah, just install the app directly from the AppStore.

**Comment by truonglac2603** [comment]
> > > TrollStore needs ipas to be decrypted. But you're better off just installing them via the AppStore.
> > 
> > 
> > Thanks for your reply, but i don't really catch it. You mean Appstore can install encrypted ipa? Or just install the app directly from Appstore?
> 
> Yeah, just install the app directly from the AppStore.

So what is the point of this ipatool? Is there any way to install those encrypted files to iDevice? Can't find any instruction about this

**Comment by JPS46225** [comment]
You can probably install them in Finder. I haven’t tried yet so I can’t say for sure.

**Comment by sonvirgo** [comment]
> You can probably install them in Finder. I haven’t tried yet so I can’t say for sure.

I found a way, use u3tool
I try to install paid app ShadowRocket
It seems to install ok from u3tool
But on first run, it asks for username and password of the person, who purchase the ipa file
Haven't tested with free app yet

**Comment by Sicksyg** [comment]
You can install the downloaded ipa packages using ideviceinstaller from [libimobiledevice](https://libimobiledevice.org/). A cross-platform FOSS library in C that plays really nicely with iOS devices.

**Comment by sonvirgo** [comment]
> You can install the downloaded ipa packages using ideviceinstaller from [libimobiledevice](https://libimobiledevice.org/). A cross-platform FOSS library in C that plays really nicely with iOS devices.

will it be possible to dowmload older version of the ipa for older iOS?
