### ISSUE TITLE
what do I do about 2FA code?

### ISSUE THREAD

**Issue by Foxiseminger** [majd/ipatool#279]
### What happened?

Its asking for 2FA code, but where do i get my 2-step verification code?

### Version

Latest

### Relevant log output

```shell
10:25PM ERR error="Did you forget your password?" success=false
```

**Comment by Foxiseminger** [comment]
ok nvm what is this?
10:31PM INF enter passphrase to unlock "C:\\Users\\F## I########\\.ipatool" (this is separate from your Apple ID password):

**Comment by gguidotti** [comment]
Hi @Foxiseminger , what did you do to get the 2FA? I'm stuck at the "enter 2FA code" prompt and have no idea how to get it. I usually get a system notification when dealing with other services but not this time

**Comment by invertostringhe** [comment]
Same here, also if using an app-specific password.

**Comment by mtagliafico** [comment]
Same here

**Comment by nice2m** [comment]
Not a problem,while trying via:``

**Comment by majd** [comment]
You can get the 2FA code from an Apple device that is logged in to that Apple ID. There is an option to retrieve a 2FA code via the Settings app on-demand.
