### ISSUE TITLE
Obtain license for apps without an iOS device

### ISSUE THREAD

**Issue by kimjhooo** [majd/ipatool#28]

**Comment by majd** [comment]
Unfortunately, this is currently not supported. As mentioned in the [Common Knowledge](https://github.com/majd/ipatool#common-knowledge) section, you need to have a license for the app you are trying to download. I'll leave this issue open as a feature request, in case someone would like to contribute by adding support for this.

**Comment by vadimszzz** [comment]
Crap. What's the case to use this tool then?

**Comment by majd** [comment]
This is now supported with the `purchase` command which was added in [version 1.1.0](https://github.com/majd/ipatool/releases/tag/v1.1.0).
