### ISSUE TITLE
ERR error="unknown shorthand flag: 'i' in -i" 

### ISSUE THREAD

**Issue by kiristern** [majd/ipatool#282]
### What happened?

is the flag `--app-id` supposed to point to `<key>softwareVersionExternalIdentifiers</key>` ?

I am trying to download a specific app version using the Build version number (obtained in `iTunesMetadata.plist`, see [here](https://github.com/qnblackcat/How-to-Downgrade-apps-on-AppStore-with-iTunes-and-Charles-Proxy/issues/8#issuecomment-1272240225) for finding previous version IDs). However,  only the flag `-b` is available to specify for download. Is it possible to override with `-i` flag to retrieve the `.ipa` of a specific version?

Hoping this would also solve this [issue](https://github.com/majd/ipatool/issues/281) at the same time.

### Version

2.1.4

### Relevant log output

```shell
$ ipatool download -i 865924040
3:33PM ERR error="unknown shorthand flag: 'i' in -i" success=false

$ ipatool download --app-id 865924040 -b com.tribab.tricount.test 
3:46PM ERR error="unknown flag: --app-id"
```

**Comment by mfuhrer** [comment]
This feature was added in #263 (after the v2.1.4 release). Have you tried building from the latest source code?
```shell
$ go build -o ipatool
$ ipatool download -i 865924040
downloading   0% | 
2:59PM ERR error="received error: An unknown error has occurred" success=false
``` 
For me, the flag works - but I then run into the download error (not specific to your app id) which is probably a separate issue.
