### ISSUE TITLE
Failure to pop up 2FA verification code when signing in with iCloud on China's cloud in Guizhou

### ISSUE THREAD

**Issue by xiaobai151** [majd/ipatool#287]
### What happened?

Failure to pop up 2FA verification code when signing in with iCloud on China's cloud in Guizhou

### Version

New

**Comment by AppleGeek2005** [comment]
when it asked me for the code I wrote
"000000" 
(six zeros)
and it passed

**Comment by kylin24k** [comment]
I have the same issue in the same location.

**Comment by majd** [comment]
Authentication was fixed in #316.
