### ISSUE TITLE
ipatool won't open apps

### ISSUE THREAD

**Issue by mpermperpisang** [majd/ipatool#288]
### What happened?

```
ipatool auth login -e <my apps store email> -p <my apps store password>
ipatool search <my apps>
ipatool download --bundle-identifier <my apps bundle id> --output my_apps.ipa
```

it download .ipa file successfully
but when I tried to install n open in LambdaTest, it won't open at all. just a blink then close
i don't know if any of my steps is wrong because i already login with the same email in my device farm with the email for ipatool

### Version

2.1.4

**Comment by majd** [comment]
You need to have logged in previously with the Apple ID that owns the app on the device that you are trying to install the app on.
