### ISSUE TITLE
brew install does not find ipatool

### ISSUE THREAD

**Issue by Volker2358** [majd/ipatool#292]
### What happened?

If I try to install IPATOOL via Ubuntu terminal, it. is not found in the repo. I get this back:
see codeblock

Thanks for your help
Volker

### Version

ipatool-2.1.4-linux-amd64.tar.gz

### Relevant log output

```shell
$ brew tap majd/repo
$ brew install ipatool
Warning: No available formula with the name "ipatool". Did you mean atool, ipmitool or apktool?
==> Searching for similarly named formulae...
==> Formulae
atool                      ipmitool                   apktool
```

**Comment by suhrmann** [comment]
Homebrew is for MacOS only! You can find the linux binaries in the [Releases](https://github.com/majd/ipatool/releases/latest).

**Comment by Tarun5139** [comment]
Hello I am not able to login in ipa tool 
see this ?
<img width="1691" alt="Screenshot 2024-09-26 at 6 55 29 PM" src="https://github.com/user-attachments/assets/87fe044a-011b-47dd-a57e-65399d5fc769">

**Comment by Tarun5139** [comment]
What is current command for it Could please help with it for me
