### ISSUE TITLE
The program cannot continue to be used. Login erro

### ISSUE THREAD

**Issue by ghost** [majd/ipatool#298]
### What happened?

Hi there, I've encountered a new issue. Around yesterday, when attempting to log in, Apple's side would report a 404 error, which prevented the login process and halted the entire program from proceeding.

### Version

2.1.4

### Relevant log output

```shell
404
```

**Comment by Coderus-Robin** [comment]
Is this then returning results like `INF email= name=" " success=true` as that is what I am seeing upon trying to log in where the name & email returned are blank.
AlsoI  get a 2FA request if I get the password wrong but not if I get it correct....

**Comment by ZhichaoZhan** [comment]
> Is this then returning results like `INF email= name=" " success=true` as that is what I am seeing upon trying to log in where the name & email returned are blank. Also I get a 2FA request if I get the password wrong but not if I get it correct....

Hi, thank you very much for your response. When I enter the correct ID and password, it should show email= name=" " success=true. After debugging, I found that Apple returned a 404 error, indicating the request was rejected. The ipatool logic did not account for a 404 response, which resulted in it returning success=true. In reality, the request had already received a 404 error. I'm not sure if anyone else has encountered this issue or if there are any solutions available.

**Comment by Coderus-Robin** [comment]
Well this continues to be an issue for me today, I had hoped it was temporary

**Comment by vijaytholpadi** [comment]
Same issue for me as well

**Comment by hzlzh** [comment]
`INF email= name=" " success=true`
same here

**Comment by FlashTang** [comment]
same here

**Comment by mayaijung** [comment]
same here. I wonder if the URL is no longer valid and we need to find different URL for auth, purchase and download

**Comment by majd** [comment]
The issue should be fixed in #316.
