### ISSUE TITLE
Doesn't work on High Sierra

### ISSUE THREAD

**Issue by joshblah555** [majd/ipatool#3]
`dyld: Library not loaded: @rpath/libswiftCore.dylib`

Works fine with Catalina and Big Sur...

**Comment by majd** [comment]
Thanks for reporting this. It's probably due to the fact that High Sierra does not include the standard swift libraries and they need to be shipped with every release. As I don't intend to support old versions of macOS, I've went ahead and bumped the minimum supported target to macOS 10.15.

**Comment by yueziii** [comment]
https://support.apple.com/kb/DL1998

**Comment by yueziii** [comment]
for those who are using old version of MacOS, can download and install the swift runtime. then it will works again
