### ISSUE TITLE
Missing 2FA, no iOS device

### ISSUE THREAD

**Issue by TheMagicalKing** [majd/ipatool#301]
### What happened?

2FA-verifications not available, neither e-mail or SMS

No iOS/MacOS device available to force 2FA from settings.

### Version

2.1.4-windows

**Comment by mikehouse** [comment]
Confirm, 2FA is not sent. May be relates to this https://github.com/fastlane/fastlane/pull/26415

**Comment by mikehouse** [comment]
Small update, I was using wrong password, after login with right password I got this issue https://github.com/majd/ipatool/issues/298. Thank you.

**Comment by majd** [comment]
Authentication was fixed in #316.
