### ISSUE TITLE
Mishandling of authorization

### ISSUE THREAD

**Issue by TheMagicalKing** [majd/ipatool#302]
### What happened?

When using authenticating through the

auth login -e [email]

Command it attempts to authenticate, on correct password it goes straight for passphrase and skips 2FA, causing the authentication to be false:

INF email= name=" " success=true

No logs available, action performed on windows

### Version

2.1.4-windows

**Comment by TheMagicalKing** [comment]
> ### What happened?
> 
> When using authenticating through the
> 
> auth login -e [email]
> 
> Command it attempts to authenticate, on correct password it goes straight for passphrase and skips 2FA, causing the authentication to be false:
> 
> INF email= name=" " success=true
> 
> No logs available, action performed on windows
> ### Version
> 
> 2.1.4-windows
> ### Relevant log output
> 
> _No response_

Assumed to be root cause of #298 and other issues with the informational output of successful authentication.

**Comment by majd** [comment]
The issue should be fixed in #316.
