### ISSUE TITLE
An unknown error has occurred

### ISSUE THREAD

**Issue by jc96110** [majd/ipatool#305]
### What happened?

![image](https://github.com/user-attachments/assets/3ab2059e-d1e3-46bf-b2e0-46f86836620f)

### Version

latest

**Comment by dschm1dt** [comment]
I am getting the same error, even if I have manually purchased the app before

**Comment by jeanplevesque** [comment]
I get the same error.
Searching works fine, but downloading doesn't work, even with the TestFlight app.

**Comment by BreakfastSerial** [comment]
I'm facing the same issue, attempting to download the ipa for an application (`./ipatool-2.1.4-linux-amd64 download -b com.ookla.speedtest --verbose`), I was able to find using `./ipatool-2.1.4-linux-amd64 search "test"`, using the pre-built binary 2.1.4-linux-amd64.

**Comment by balla-mobisec** [comment]
Facing the same issue too, if someone got it to work please update

**Comment by shoriful19** [comment]
@jc96110 any update on this?

**Comment by OneXeor** [comment]
Faced with the same issue

**Comment by majd** [comment]
The issue should be fixed in #316.
