### ISSUE TITLE
what is a passphrase and how do i obtain it?

### ISSUE THREAD

**Issue by Tym0nq** [majd/ipatool#306]
### Description

i need help with getting my passphrase, i dont know where  to find it
![cmd_dIHr0bzdkn](https://github.com/user-attachments/assets/4c9d5332-8a96-485e-a50b-805037363b07)

**Comment by billxsand** [comment]
Also wondering this lmao

**Comment by WaspStar** [comment]
Same here too, no passphrase set on the device or account, so not sure how to get around this?

**Comment by ArushCodes** [comment]
Plus one lol.

**Comment by 0utlawActual** [comment]
It may not be clear but this is a passphrase you create from scratch, and you will use it every time you need to do some actions with the tool. think of it as a password you create for ipatool

**Comment by ArushCodes** [comment]
> It may not be clear but this is a passphrase you create from scratch, and you will use it every time you need to do some actions with the tool. think of it as a password you create for ipatool

I get that, but where do I actually create it? I'm not prompted to make it ever, just asked for it.

**Comment by 0utlawActual** [comment]
You should get it when you do your auth process, you might have to do 
`./ipatool auth revoke` and start over
