### ISSUE TITLE
How can i use this on windows

### ISSUE THREAD

**Issue by weasdrsitegoogle** [majd/ipatool#308]
When I opened the program, it said this is a command line tool. You need to open cmd.exe and run it from there.

when i opened cmd.exe using windows + r and tried to run "ipatool auth" it said 'ipatool' is not recognized as an internal or external command, operable program or batch file.   Can someone help me

**Comment by handersonsousa** [comment]
still with the same problem why they created this tool so hard to use

**Comment by PJMarcum** [comment]
Clearly the file name is not "ipatool" to you cannot run "ipatool". You need to run the real .exe name. For example: ipatool-2.1.4-windows-amd64.exe auth
