### ISSUE TITLE
Allow setting the Software Version External Identifier

### ISSUE THREAD

**Issue by jkrosado** [majd/ipatool#31]
SVEIDs are (presumably) used by iTunes to grab app versions for downloading a specific version of an app. AppStore++, Adowngrader, and App Admin use this to downgrade apps, and I believe the App Store itself uses it when you're on an older version of iOS than the latest version supports.

Adowngrader is [open source](https://github.com/H6nry/H6nry-iPhone/tree/master/adowngrader), maybe something helpful is there.

**Comment by majd** [comment]
Unfortunately, the API that ipatool uses does not support setting external version identifiers (at least, as far as I know). I'll leave this issue open for future reference and because it's related to #6.

**Comment by majd** [comment]
Tracked in #6
