### ISSUE TITLE
Country code un==invalid 

### ISSUE THREAD

**Issue by xabode** [majd/ipatool#310]
### What happened?

ERR error="country code is invalid: country code mapping for store front () was not found" success=false

### Version

last

**Comment by mlch911** [comment]
same here.

**Comment by BreakfastSerial** [comment]
Check out previous issues (https://github.com/majd/ipatool/issues/307), where this has already been solved. Also, for the future, try to be more elaborate, your issue lacks loads of information.

**Comment by majd** [comment]
The issue should be fixed in #316.
