### ISSUE TITLE
Unknown error occurred while downloading

### ISSUE THREAD

**Issue by LushanCloud** [majd/ipatool#311]
### What happened?

The country code is set and I can search fine but when I download it I get an error。ipatool installed using brew

### Version

ipatool version 2.1.4

### Relevant log output

```shell
ipatool download -b com.miHoYo.Yuanshen
downloading   0% |                                                 | ( 0/ 1 B) 2:36PM ERR error="received error: An unknown error has occurred" success=false
```

**Comment by silviafiat** [comment]
Same issue here

**Comment by amccoy-cyber** [comment]
Same here. I set the storefront code in Keychain (on MacOS) and am able to now search for apps with no issues (previously could not search without manually setting storefront code). However, after obtaining the license on the relevant Apple account, I am unable to download the .ipa file using the bundle identifier as shown above. 

I receive...

ERR error="received error: An unknown error has occurred" success=false

**Comment by dnd21052002** [comment]
same issue here, can anyone fix this?

**Comment by AltayAkkus** [comment]
@dnd21052002 @amccoy-cyber @silviafiat @LushanCloud
I am currently trying to work this out, can you guys please tell me the output of this:
`ipatool purchase --bundle-identifier com.burbn.instagram`

You can use any other bundle-identifier, no stress there, but I think the root cause of all these issues is that the authentication is broken alltogether.

The request send on a "succesful login" returns with a status code of 404, I think Apple may have closed that endpoint.

**Comment by fantasyxby** [comment]
> @dnd21052002 @amccoy-cyber @silviafiat @LushanCloud I am currently trying to work this out, can you guys please tell me the output of this: `ipatool purchase --bundle-identifier com.burbn.instagram`
> 
> You can use any other bundle-identifier, no stress there, but I think the root cause of all these issues is that the authentication is broken alltogether.
> 
> The request send on a "succesful login" returns with a status code of 404, I think Apple may have closed that endpoint.

$ ipatool purchase --bundle-identifier com.burbn.instagram
9:39AM ERR error="failed to purchase item with param 'STDQ': This Apple account could not be found, so it cannot be used in the iTunes Store at this time. Please try again later." success=false

**Comment by MAyazShah** [comment]
Hello could anyone give a solution to this? I am also stopped on this part to download IPA files

**Comment by AltayAkkus** [comment]
Yea it seems like the login alltogether is broken, the login request is malformed the only reason why u see "success" is because ipatool didnt account for this.

So we gotta find the new endpoint, I'll be on it tmrw.

**Comment by qsirwyk** [comment]
same herer

**Comment by MAyazShah** [comment]
By the way I am running my MacBook Pro, Is the issue because of macOS? I haven't tried it on windows.

**Comment by ypwcharles** [comment]
the same on Windows

MAyazShah ***@***.***>于2024年11月27日 周三下午7:07写道：

**Comment by xsha256** [comment]
Same issue here

**Comment by mayoubs** [comment]
Hi, here is the log when trying to donwload 
`masefiatti@Mohameds-MacBook-Air ~ % ipatool download --verbose -b com.vigicorp.iswigo -o Gerermescomptes.ipa
downloading   0% |                                                                                                                                                    | ( 0/ 1 B) 11:09PM DBG error="received error: An unknown error has occurred" metadata={"Data":{"CustomerMessage":"An unknown error has occurred","FailureType":"5002","Items":null},"Headers":{"Apple-Originating-System":"MZFinance","Apple-Seq":"0.0","Apple-Timing-App":"6 ms","Apple-Tk":"false","B3":"98d9a9c9bf609ac9ce17a6b3d7986ba4-203e0a6cdcb16fae","Cache-Control":"private; no-cache; no-store; no-transform; must-revalidate; max-age=0","Connection":"keep-alive","Date":"Sun, 08 Dec 2024 22:09:54 GMT","Edge-Control":"no-store; cache-maxage=0","Expires":"Sun, 08 Dec 2024 22:09:54 GMT","Itspod":"25","Pod":"25","Server":"Apple","Set-Cookie":"itspod=25; version=\"1\"; expires=Wed, 08-Jan-2025 22:09:54 GMT; path=/; domain=.apple.com; mzf_in=3250013; version=\"1\"; path=/WebObjects; domain=.apple.com; secure; HttpOnly; mzf_dr=0; version=\"1\"; expires=Thu, 01-Jan-1970 00:00:00 GMT; path=/WebObjects; domain=.apple.com","Strict-Transport-Security":"max-age=31536000; includeSubdomains","X-Apple-Application-Instance":"3250013","X-Apple-Application-Site":"MR22","X-Apple-Jingle-Correlation-Key":"TDM2TSN7MCNMTTQXU2Z5PGDLUQ","X-Apple-Lokamai-No-Cache":"true","X-Apple-Orig-Url":"https://p25-buy.itunes.apple.com/WebObjects/MZFinance.woa/wa/volumeStoreDownloadProduct?guid=82ADFBE35D7C","X-Apple-Request-Uuid":"98d9a9c9-bf60-9ac9-ce17-a6b3d7986ba4","X-Apple-Translated-Wo-Url":"/WebObjects/MZFinance.woa/wa/volumeStoreDownloadProduct?guid=82ADFBE35D7C","X-B3-Spanid":"203e0a6cdcb16fae","X-B3-Traceid":"98d9a9c9bf609ac9ce17a6b3d7986ba4","X-Content-Type-Options":"nosniff","X-Daiquiri-Instance":"daiquiri:14236001:mr55p00it-qukt05050701:7987:24RELEASE242:daiquiri-amp-commerce-legacy-int-001-mr; daiquiri:14626002:mr55p00it-qukt01020301:7987:24RELEASE242:daiquiri-amp-commerce-pci-ext-001-mr","X-Frame-Options":"SAMEORIGIN","X-Responding-Instance":"MZFinance:3250013:::","X-Webobjects-Loadaverage":"59","X-Xss-Protection":"1; mode=block"},"StatusCode":200}
11:09PM ERR error="received error: An unknown error has occurred" success=false
`

**Comment by FoneG** [comment]
the same on Mac

**Comment by AltayAkkus** [comment]
> the same on Mac，Is there a solution？@majd @AltayAkkus 

Purchase is broken, I am working on a solution just as the colleagues at ipsw.

**Comment by majd** [comment]
Authentication and downloading was fixed in #316. Let's use the issue #284 to track the purchase issue.

**Comment by izzoa** [comment]
> Authentication and downloading was fixed in #316. Let's use the issue #284 to track the purchase issue.

Hi @majd , respectfully, I'm not sure downloading is fixed. Authentication seems to be fine and I'm able to log in a search, but any download yields this result:

```
./ipatool download -b com.aktiia.aktiia --verbose
downloading   0% |                                                                                                                     | ( 0/ 1 B) 2:37AM DBG 
error="received error: An unknown error has occurred" metadata={
  "Data": {
    "CustomerMessage": "An unknown error has occurred",
    "FailureType": "5002",
    "Items": null
  },
  "Headers": {
    "Apple-Originating-System": "MZFinance",
    "Apple-Seq": "0.0",
    "Apple-Timing-App": "9 ms",
    "Apple-Tk": "false",
    "B3": "827b996ab42e9bec56c5fa126c401c3e-21ae1eed15e8a08a",
    "Cache-Control": "private; no-cache; no-store; no-transform; must-revalidate; max-age=0",
    "Connection": "keep-alive",
    "Date": "Fri, 13 Dec 2024 08:37:22 GMT",
    "Edge-Control": "no-store; cache-maxage=0",
    "Expires": "Fri, 13 Dec 2024 08:37:22 GMT",
    "Itspod": "25",
    "Pod": "25",
    "Server": "Apple",
    "Set-Cookie": "itspod=25; version=\"1\"; expires=Mon, 13-Jan-2025 08:37:22 GMT; path=/; domain=.apple.com; mzf_in=3250084; version=\"1\"; path=/WebObjects; domain=.apple.com; secure; HttpOnly; mzf_dr=0; version=\"1\"; expires=Thu, 01-Jan-1970 00:00:00 GMT; path=/WebObjects; domain=.apple.com",
    "Strict-Transport-Security": "max-age=31536000; includeSubdomains",
    "X-Apple-Application-Instance": "3250084",
    "X-Apple-Application-Site": "MR22",
    "X-Apple-Jingle-Correlation-Key": "QJ5ZS2VUF2N6YVWF7IJGYQA4HY",
    "X-Apple-Lokamai-No-Cache": "true",
    "X-Apple-Orig-Url": "https://p25-buy.itunes.apple.com/WebObjects/MZFinance.woa/wa/volumeStoreDownloadProduct?guid=AA00278ED4D1",
    "X-Apple-Request-Uuid": "827b996a-b42e-9bec-56c5-fa126c401c3e",
    "X-Apple-Translated-Wo-Url": "/WebObjects/MZFinance.woa/wa/volumeStoreDownloadProduct?guid=AA00278ED4D1",
    "X-B3-Spanid": "21ae1eed15e8a08a",
    "X-B3-Traceid": "827b996ab42e9bec56c5fa126c401c3e",
    "X-Content-Type-Options": "nosniff",
    "X-Daiquiri-Instance": "daiquiri:14236001:mr55p00it-qukt05050701:7987:24RELEASE242:daiquiri-amp-commerce-legacy-int-001-mr; daiquiri:14626003:mr55p00it-qukt02032101:7987:24RELEASE242:daiquiri-amp-commerce-pci-ext-001-mr",
    "X-Frame-Options": "SAMEORIGIN",
    "X-Responding-Instance": "MZFinance:3250084:::",
    "X-Webobjects-Loadaverage": "112",
    "X-Xss-Protection": "1; mode=block"
  },
  "StatusCode": 200
}
```

**Comment by NimaSoroush** [comment]
I am having the same issue

`{
  "Data": {
    "CustomerMessage": "An unknown error has occurred",
    "FailureType": "5002",
    "Items": null
  },
  "Headers": {
    "Apple-Originating-System": "MZFinance",
    "Apple-Seq": "0.0",
    "Apple-Timing-App": "5 ms",
    "Apple-Tk": "false",
    "B3": "afb5de875b43f8692c69a938b065da62-1f6c5dcf4b47a7e4",
    "Cache-Control": "private; no-cache; no-store; no-transform; must-revalidate; max-age=0",
    "Connection": "keep-alive",
    "Date": "Sat, 14 Dec 2024 23:41:34 GMT",
    "Edge-Control": "no-store; cache-maxage=0",
    "Expires": "Sat, 14 Dec 2024 23:41:34 GMT",
    "Itspod": "25",
    "Pod": "25",
    "Server": "Apple",
    "Set-Cookie": "itspod=25; version=\"1\"; expires=Tue, 14-Jan-2025 23:41:34 GMT; path=/; domain=.apple.com; mzf_in=3250071; version=\"1\"; path=/WebObjects; domain=.apple.com; secure; HttpOnly; mzf_dr=0; version=\"1\"; expires=Thu, 01-Jan-1970 00:00:00 GMT; path=/WebObjects; domain=.apple.com",
    "Strict-Transport-Security": "max-age=31536000; includeSubdomains",
    "X-Apple-Application-Instance": "3250071",
    "X-Apple-Application-Site": "MR22",
    "X-Apple-Jingle-Correlation-Key": "V6255B23IP4GSLDJVE4LAZO2MI",
    "X-Apple-Lokamai-No-Cache": "true",
    "X-Apple-Orig-Url": "https://p25-buy.itunes.apple.com/WebObjects/MZFinance.woa/wa/volumeStoreDownloadProduct?guid=5ADB1611F6E3",
    "X-Apple-Request-Uuid": "afb5de87-5b43-f869-2c69-a938b065da62",
    "X-Apple-Translated-Wo-Url": "/WebObjects/MZFinance.woa/wa/volumeStoreDownloadProduct?guid=5ADB1611F6E3",
    "X-B3-Spanid": "1f6c5dcf4b47a7e4",
    "X-B3-Traceid": "afb5de875b43f8692c69a938b065da62",
    "X-Content-Type-Options": "nosniff",
    "X-Daiquiri-Instance": "daiquiri:14236001:mr55p00it-qukt05050701:7987:24RELEASE242:daiquiri-amp-commerce-legacy-int-001-mr; daiquiri:14626002:mr55p00it-qukt01020301:7987:24RELEASE242:daiquiri-amp-commerce-pci-ext-001-mr",
    "X-Frame-Options": "SAMEORIGIN",
    "X-Responding-Instance": "MZFinance:3250071:::",
    "X-Webobjects-Loadaverage": "151",
    "X-Xss-Protection": "1; mode=block"
  },
  "StatusCode": 200
}`

**Comment by YoungFizzler** [comment]
+1 on my macbook m1 pro

**Comment by itstalon** [comment]
+1, MacBook intel silicon

**Comment by MAyazShah** [comment]
Hi - @tangbl93 @YoungFizzler @itstalon has the download unknown error solved?

**Comment by MAyazShah** [comment]
@majd @AltayAkkus have you fixed download issue? Because I am still getting the same issue:
```
muhammadayazshah@Muhammad-Ayaz-Shahs-MacBook-Pro ipatool % ipatool download -b com.unitednaturalfoodsinc.myunfi
downloading   0% |                                                                                                                                                                                                                                | ( 0/ 1 B) 10:58AM ERR error="received error: An unknown error has occurred" success=false
```

**Comment by itstalon** [comment]
I've not been able to test. I am waiting for a new release... I've been searching for a fix for months. Might resort to other tools / products.

**Comment by tangbl93** [comment]
using Apple Configurator resolved

**Comment by sickerin** [comment]
I used Apple Configurator instead, below worked for me, and simple too
https://gist.github.com/n0mi1k/d5c440589025d9da770dca1cffa91d92

**Comment by vadim-belous** [comment]
The 2.1.4 Homebrew package version and the 2.1.5 latest version from the repo release page both didn't work on macOS Silicon ;(

**Comment by fabiotorre** [comment]
Hi guys, I just tried version 2.1.5, and even though I went through the hoops of adding the storefront to the keychain and so being able to search apps, download still does not work, MacBook M1, Sequoia. I didn't try the Configurator solution yet because it won't solve my use case. Can we reopen this issue, by any chance, as I don't seem to be the only one unable to download using 2.1.5? Thanks, anyways, for the great tool.

**Comment by vadim-belous** [comment]
> Hi guys, I just tried version 2.1.5, and even though I went through the hoops of adding the storefront to the keychain and so being able to search apps, download still does not work, MacBook M1, Sequoia. I didn't try the Configurator solution yet because it won't solve my use case. Can we reopen this issue, by any chance, as I don't seem to be the only one unable to download using 2.1.5? Thanks, anyways, for the great tool.

I’m stuck with the same issue and haven’t been able to solve it for a while using the methods mentioned here (adding a storefront). Maybe an older version will work. Maybe Apple just changed their API and there is no simple way to fix this issue

**Comment by wittawatu** [comment]
In my case just put the "..." (Quotes) for bubble name is working
change from    ipatool download -b com.app.bundle   to  ipatool download -b "com.app.bundle"
This safe my day
M1 Pro

**Comment by nathantyme** [comment]
> In my case just put the "..." (Quotes) for bubble name is working change from ipatool download -b com.app.bundle to ipatool download -b "com.app.bundle" This safe my day M1 Pro

Recommend this way, I tried many commands, but only this works like a charm
