### ISSUE TITLE
MAJOR: Login broken

### ISSUE THREAD

**Issue by AltayAkkus** [majd/ipatool#312]
So as you may notice in the Issues tab, many users face problems using this tool at all. The download, purchase and purchase commands are broken.

I think the root cause is that the login method crafts a 
`POST https://p25-buy.itunes.apple.com/WebObjects/MZFinance.woa/wa/authenticate?guid=$guid`
but the response is a 404, this endpoint does not exist anymore.

The `auth login` command still returns `success=true` because the function does not check the status code properly, but in fact **you are never logged in**.

Let's start the discussion/remediation here on how we can fix the login.

- [ ] Search for the new login endpoint
@majd did you take the requests from an iPhone, or just a regular Mac?

- [ ] Implement new login endpoint

Let's keep the discussions regarding the root-cause in this issue.

**Comment by dschm1dt** [comment]
If it is the login method, maybe the [comment](https://github.com/majd/ipatool/issues/284#issuecomment-2431709898) can be helpful

**Comment by MAyazShah** [comment]
Hey @AltayAkkus have you tried is it working or not?

**Comment by AltayAkkus** [comment]
> Hey @AltayAkkus have you tried is it working or not? 

Have I tried what? This thread is only discussing the problem.

**Comment by Oisann** [comment]
I noticed that you get a 200 (but a plist error) if you provide invalid credentials, but 404 and no content if you provide valid ones.
Changing the [Content-Type](https://github.com/majd/ipatool/blob/63ee6fc6a42a89d51c9caac632cefd65218825ab/pkg/appstore/appstore_login.go#L120C33-L120C54) to `application/xml` of the login request will always return 200 and a plist error of -5000 (`Check the account information you entered and try again.`).

So my guess is that we're missing some data to POST and that they also check the Content-Type header now. I will do some more research...

**Comment by 538742** [comment]
> I used this fork: https://github.com/rejail/ipatool and compiled it on windows, and it worked fine.

This modification redirects network requests to an unauthorized server. DO NOT use this version, if you don't want to expose your sensitive data

**Comment by AltayAkkus** [comment]
> I used this fork: https://github.com/rejail/ipatool and compiled it on windows, and it worked fine.

nice work, threat actor!

**Do not use that tool, at all.**

**Comment by AltayAkkus** [comment]
So the folks over at https://github.com/blacktop/ipsw/pull/595 fixed the download, but not the purchase (yet). So you can succesfully download the .IPAs from Apps which are already purchased by your user account.

I will try to work on the purchase part, if you want to download something use ipsw for now, or integrate it into this repo it shouldn't be hard (since it's a fork from ipatool).

**Comment by Oisann** [comment]
Awesome! I'll backport this tomorrow morning (12h from now), unless someone else will do it by then.

**Comment by sevenpastzeero** [comment]
> 
> This modification redirects network requests to an unauthorized server. DO NOT use this version, if you don't want to expose your sensitive data

Thank you for the warning. I did not know about the  unauthorized server. Glad you informed me not to use this fork.




> 
> nice work, threat actor!

There is no need to call me that. I did not intend a malicious act. I just wanted "ipatool" to work on windows. You could've explained what I did wrong, and warn me.

**Comment by AltayAkkus** [comment]
> > 
> > nice work, threat actor!
> 
> There is no need to call me that. I did not intend a malicious act. I just wanted "ipatool" to work on windows. You could've explained what I did wrong, and warn me.

Sorry I looked at the repo and assumed it was yours, and the account seems to fork a lot of repos just to add a single malicious commit, so I thought this is some kind of bot campaign

**Comment by nikias** [comment]
This works for me: https://github.com/majd/ipatool/pull/314

**Comment by Oisann** [comment]
> This works for me: #314

I ported all the changes from https://github.com/blacktop/ipsw/pull/595 earlier today, but I couldn't get it to be stable on my test account.

**Comment by PJMarcum** [comment]
I came to this thread hoping to figure out why I cannot get past "INF enter 2FA code:" I enter my username and password but I am never shown a 2FA code on my iOS device. Any ideas?

**Comment by tux-mind** [comment]
#316 should have fixed this. Is it working for you?
It has been merged into `main` already with 8a23d6fadd6180d35614c2f7bcca0dccd6d9a64e .

**Comment by sevenpastzeero** [comment]
@538742 Is this tool good? https://github.com/1Emilis1/iPATool-EZ

**Comment by majd** [comment]
The issue should be fixed in #316.
