### ISSUE TITLE
Add support for building for iOS

### ISSUE THREAD

**Issue by Al4ise** [majd/ipatool#52]
I am not sure if this is in the project's scope, but it would be nice if it could be great if support for running on jailbroken iOS was added

**Comment by langkhach270389** [comment]
ipatool-py python version. https://github.com/NyaMisty/ipatool-py .
You can run it on ios using the pyto app. Or run on linux, windows,..

**Comment by majd** [comment]
Prebuilt binaries for iOS are now included in releases starting from [version 1.1.2](https://github.com/majd/ipatool/releases/tag/v1.1.2).

**Comment by Ender890** [comment]
Huh, cool. Is this the only build version for ios? I cant build the master tree, it says some errors about the keyring parameter not found or something
