### ISSUE TITLE
dyld: Library not loaded: @rpath/libswift_Concurrency.dylib

### ISSUE THREAD

**Issue by Haxonate** [majd/ipatool#53]
How to fix?  ipatool 1.0.9
<img width="682" alt="Screenshot 2022-03-21 at 14 46 35" src="https://user-images.githubusercontent.com/43535933/159246195-7a8edc30-8215-4f60-8465-edd6a727cdf8.png">

**Comment by tom-snow** [comment]
Same problem too...

**Comment by tom-snow** [comment]
But... I don't want install Xcode(It's Toooooooo huge)

**Comment by Haxonate** [comment]
> > How to fix? ipatool 1.0.9
> > <img alt="Screenshot 2022-03-21 at 14 46 35" width="682" src="https://user-images.githubusercontent.com/43535933/159246195-7a8edc30-8215-4f60-8465-edd6a727cdf8.png">
> 
> Solution: https://github.com/majd/ipatool/wiki/FAQ#troubleshooting

Thx, I’ll try, but I have Xcode

**Comment by majd** [comment]
Duplicate of #50. You need to either install the latest Xcode version or the Swift toolchain. Instructions are available [on the wiki](50).
