### ISSUE TITLE
libswift_Concurrency.dylib not loaded

### ISSUE THREAD

**Issue by ahmadhashemi** [majd/ipatool#60]
Thanks for the great work, especially with the 1.1.0 release. I have no problem running this tool on macOS 12.2. But I get this error on macOS 11.1:

dyld: Library not loaded: @rpath/libswift_Concurrency.dylib
  Referenced from: /usr/local/bin/ipatool
  Reason: image not found

**Comment by liorazi** [comment]
Check majd's answer here:
https://github.com/majd/ipatool/wiki/FAQ#troubleshooting
