### ISSUE TITLE
dyld: Library not loaded: @rpath/libswift_Concurrency.dylib

### ISSUE THREAD

**Issue by CokePokes** [majd/ipatool#61]
Hey majd, 

Installed through brew on Mac 10.15.4. 
xCode 11.4.1

```Referenced from: /usr/local/bin/ipatool   Reason: image not found.```

Perhaps can be fixed by added optional flag on libswift_Concurrency.dylib.

Can't try it out myself since I refuse to update xcode & break my tweak dev environment.

**Comment by majd** [comment]
Hey, you need to either install the latest Xcode version or the Swift toolchain. Instructions are available [on the wiki](https://github.com/majd/ipatool/wiki/FAQ#troubleshooting).

Duplicate of #50.

**Comment by CokePokes** [comment]
How the hell did I miss that? My bad.
