### ISSUE TITLE
dyld: Library not loaded: @rpath/libswift_Concurrency.dylib

### ISSUE THREAD

**Issue by Am1nCmd** [majd/ipatool#67]
Hi there, I was having an issue while installing ipatool

 ✘ am1ncmd@Hack1ntosh  ~  ipatool
dyld: Library not loaded: @rpath/libswift_Concurrency.dylib
  Referenced from: /usr/local/bin/ipatool
  Reason: image not found
[1]    10096 abort      ipatool

**Comment by majd** [comment]
Duplicate of #50. You need to either install the latest Xcode version or the Swift toolchain. Instructions are available [on the wiki](https://github.com/majd/ipatool/wiki/FAQ#troubleshooting).
