### ISSUE TITLE
Unknown Error occurred when purchasing any app

### ISSUE THREAD

**Issue by ryujincoder** [majd/ipatool#70]
### What happened?

I was downloading google assistant via ipatool, but (i used the --purchase addon) and it did not work, so then I tried other apps that use the purchase command and it still did not work
<img width="586" alt="Screen Shot 2022-05-01 at 4 47 33 PM" src="https://user-images.githubusercontent.com/77733509/166169589-745cfa41-3cc9-4d07-8651-b1e946c9a170.png">
.

### Version

The Latest

**Comment by 0xkuj** [comment]
run ipatool auth login and login with your account again, it will be fixed
