### ISSUE TITLE
No error message from pipeline

### ISSUE THREAD

**Issue by ChialeKuan** [majd/ipatool#72]
### What happened?

```shell
ipatool download -b com.emberlink.foodby --log-level debug> temp.log 2>&1
ipatool download -b com.emberlink.foodby --log-level debug> temp.log
ipatool download -b com.emberlink.foodby | tee temp.log
ipatool download -b com.emberlink.foodby 2>&1 | tee temp.log
```
Tried these two commands. If I don't use pipe, I can get error response (as expected)
```shell
❌	[Error] Your Apple ID does not have a license for this app. Use the "purchase" command or the "--purchase" to obtain a license.
```
 But I can not get any log with pipe

### Version

1.1.0

**Comment by ryujincoder** [comment]
Use the "purchase" command or the "--purchase" to obtain a license.

**Comment by ChialeKuan** [comment]
I know I don't have a license. Just I wanna get an error message dumped to temp.log, but there isn't.

**Comment by ChialeKuan** [comment]
> Use the "purchase" command or the "--purchase" to obtain a license.

I know I don't have a license. Just I wanna get an error message dumped to temp.log, but there isn't.
