### ISSUE TITLE
Problem with 2FA Authentication process

### ISSUE THREAD

**Issue by sbakhour** [majd/ipatool#82]
This is a recurring issue, this morning for example with my first login auth it did not ask me for a 2FA & the login was successful,after downloading an app and everything was fine, once the token expired, it asked me to re-authenticate again, and here is the issue, it asks for 2FA but I never receive it. I tried to re-authenticate again and it always never sends the 2FA Code. Can you please fix this problem ? Thank you in advance.

**Comment by sbakhour** [comment]
sbbakhou@88665a23f3f2 ~ % ipatool auth login
==> ⚠️	[Warning] Enter Apple ID email:
==> ⚠️	[Warning] Enter Apple ID password:
==> ℹ️	[Info] Authenticating with the App Store...
==> ⚠️	[Warning] Enter 2FA code:

zsh: suspended  ipatool auth login
sbbakhou@88665a23f3f2 ~ % ipatool auth login                          
==> ⚠️	[Warning] Enter Apple ID email:
==> ⚠️	[Warning] Enter Apple ID password:
==> ℹ️	[Info] Authenticating with the App Store...
==> ℹ️	[Info] Authenticated as 'Sam Mobilesec'.

**Comment by majd** [comment]
Can you try using a manually generated 2FA code? On macOS, `System Preferences` -> `Apple ID` -> `Get a Verification Code`.

**Comment by majd** [comment]
Does running the tool with the `--log-level debug` flag provide any useful message about the failure?

**Comment by sbakhour** [comment]
This is so funny because I tried to re-authenticate afterwards and it was successful without requesting a 2FA. I will try the `--log level debug` when it gets reproduced and keep you updated. So far I am able to authenticate without 2FA.

sbbakhou@88665a23f3f2 ~ % ipatool auth login
==> ⚠️	[Warning] Enter Apple ID email:
==> ⚠️	[Warning] Enter Apple ID password:
==> ℹ️	[Info] Authenticating with the App Store...
==> ℹ️	[Info] Authenticated as 'Sam Mobilesec'.

**Comment by majd** [comment]
Is this issue still relevant?

**Comment by sbakhour** [comment]
Hello Majd, I didn't experience this anymore with the tool. I am going to close the issue, thank you so much for your time.

**Comment by danilobjr** [comment]
@majd I'm facing this issue.

![Screen Shot 2022-09-07 at 15 45 54](https://user-images.githubusercontent.com/735556/188954562-b0b19990-0e79-4ecc-ae5c-66c19d1550a9.png)

I've tried to generate 2FA code manually in System Preferences. 

Any thoughts? Thanks in advance.
