### ISSUE TITLE
App-specific password does not work?

### ISSUE THREAD

**Issue by foxster-mp4** [majd/ipatool#90]
### What happened?

I tried to supply an app-specific password to the tool but keeps getting unknown error every time. Is this just me or does the tool not work with app-specific passwords?

### Version

1.1.2

### Relevant log output

```shell
==> ⚠️	[Warning] Enter Apple ID email:
==> ⚠️	[Warning] Enter Apple ID password:
==> 🛠	[Debug] Creating HTTP client...
==> 🛠	[Debug] Creating App Store client...
==> ℹ️	[Info] Authenticating with the App Store...
==> 🛠	[Debug] unknownError
==> ❌	[Error] An unknown error has occurred.
```

**Comment by majd** [comment]
This is not a bug - unfortunately, the private API that the tool uses does not support app-specific passwords. Until that changes, adding support for app-specific passwords in ipatool is not possible.
