### ISSUE TITLE
OSStatus error - 34018 on ios version

### ISSUE THREAD

**Issue by heinekenpsx** [majd/ipatool#91]
OSStatus error:[-34018] Internal error when a required entitlement isn't present, client has neither application-identifier nor keychain- access-groups entitlements.==> X [Error] Failed to save account data in keychain.

**Comment by majd** [comment]
Should be fixed in [version 1.1.3](https://github.com/majd/ipatool/releases/tag/v1.1.3).

**Comment by heinekenpsx** [comment]
Thank you
