### ISSUE TITLE
Can't download app in country other than my apple id region

### ISSUE THREAD

**Issue by heinekenpsx** [majd/ipatool#96]
### What happened?

I am in Vietnam, I have an apple id in the US region, when I use the -c VN command, I can download the application in the Vietnam region, but I cannot download the application in some regions such as Australia, New Zealand.  I can't do it, or is it a bug?  Please let me know

### Version

1.1.4

**Comment by majd** [comment]
This is the intended behavior. You can only download apps from the region of the Apple ID you are using.
